import { execFile } from "node:child_process";
import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { commitCommand } from "../src/cli/commit.js";
import { GitCommitWorker, verifyStagedIndexMatchesWorkspace } from "../src/commitWorker.js";
import { collectWorkspaceGitState } from "../src/gitWorkspaceState.js";
import { sha256File } from "../src/hashArtifacts.js";
import type { FinalResult } from "../src/schemas/finalResult.js";
import type { HumanDecision } from "../src/schemas/humanDecision.js";
import type { TaskBrief } from "../src/schemas/taskBrief.js";
const ex=promisify(execFile);
async function git(cwd:string,args:string[]){ const r=await ex("git",args,{cwd,encoding:"utf8"}); return r.stdout.trimEnd(); }
const brief:TaskBrief={objective:"Do it",acceptanceCriteria:["done"],nonGoals:[],codexInstruction:"edit",riskLevel:"standard"};
async function fx(opts:{decision?:HumanDecision["decision"];status?:FinalResult["status"];branch?:string;change?:boolean;evidence?:boolean;subdir?:boolean;untracked?:boolean}={}){
 const root=await mkdtemp(path.join(os.tmpdir(),"catos-commit-")); const workspace=path.join(root,"workspace"); await mkdir(workspace); await git(workspace,["init","-b",opts.branch??"catos/run-1"]); await writeFile(path.join(workspace,"a.txt"),"one\n"); await git(workspace,["-c","user.name=A","-c","user.email=a@b.c","add","."]); await git(workspace,["-c","user.name=A","-c","user.email=a@b.c","commit","-m","init"]); if(opts.change!==false) await writeFile(path.join(workspace,"a.txt"),"two\n"); if(opts.untracked) await writeFile(path.join(workspace,".rework-ok"),"ok\n");
 const runId="run-1", runsDir=path.join(root,"runs"), runDir=path.join(runsDir,runId); await mkdir(runDir,{recursive:true}); await writeFile(path.join(runDir,"input.json"),JSON.stringify({schemaVersion:1,runId,projectId:"demo",goal:"g",createdAt:new Date(0).toISOString(),configPath:path.join(root,"project.yaml")}),"utf8"); await writeFile(path.join(root,"project.yaml"),`project:\n  id: demo\n  name: Demo\n  repoPath: ${workspace}\n  baseBranch: main\ncommands:\n  typecheck: npm run typecheck\n  test: npm run test\n  build: npm run build\nworkflow:\n  maxReworkAttempts: 0\n  createCommit: false\npermissions:\n  allowNetwork: false\n  allowPush: false\n  allowMerge: false\ngit:\n  commitName: Config Name\n  commitEmail: config@local.invalid\n`);
 await writeFile(path.join(runDir,"task-brief.json"),JSON.stringify(brief),"utf8"); const workspaceState=await collectWorkspaceGitState(workspace); await writeFile(path.join(runDir,"workspace.diff"),workspaceState.diff,"utf8"); await writeFile(path.join(runDir,"validation-report.json"),JSON.stringify({schemaVersion:1,status:"PASS",workspacePath:workspace,startedAt:new Date(0).toISOString(),finishedAt:new Date(1).toISOString(),results:[]}),"utf8"); await writeFile(path.join(runDir,"review-report.json"),JSON.stringify({schemaVersion:1,verdict:"ACCEPT",summary:"ok",reviewedAcceptanceCriteria:[],blockingFindings:[],warnings:[]}),"utf8");
 const finalResult:FinalResult={schemaVersion:1,runId,status:opts.status??"ACCEPTED",finalReviewVerdict:"ACCEPT",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:opts.subdir?path.join(workspace,"sub"):workspace,finalChangedFiles:workspaceState.changedFiles,finalValidationStatus:"PASS",finalReviewReportPath:path.join(runDir,"review-report.json"),finalDiffPath:path.join(runDir,"workspace.diff"),finalValidationReportPath:path.join(runDir,"validation-report.json")}; await writeFile(path.join(runDir,"final-result.json"),JSON.stringify(finalResult),"utf8");
 const approvedEvidence=opts.evidence===false?undefined:{diffSha256:await sha256File(path.join(runDir,"workspace.diff")),validationReportSha256:await sha256File(path.join(runDir,"validation-report.json")),reviewReportSha256:await sha256File(path.join(runDir,"review-report.json"))}; const humanDecision:HumanDecision={schemaVersion:1,runId,decision:opts.decision??"APPROVE",decidedAt:new Date().toISOString(),finalResultStatus:finalResult.status,requestedChanges:[],evidenceReviewed:{taskBrief:true,finalDiff:true,validationReport:true,reviewReport:true},approvedEvidence}; await writeFile(path.join(runDir,"human-decision.json"),JSON.stringify(humanDecision),"utf8"); return {root,workspace,runId,runDir,finalResult,humanDecision}; }
async function commit(f:Awaited<ReturnType<typeof fx>>, msg?:string){return new GitCommitWorker().commit({runId:f.runId,runDir:f.runDir,finalResult:f.finalResult,humanDecision:f.humanDecision,taskBrief:brief,message:msg});}
async function blob(workspace:string,filePath:string,content:Buffer){ await writeFile(path.join(workspace,filePath),content); }
describe("Commit Worker",()=>{
 it("valid APPROVE creates commit and result, leaves clean tree",async()=>{const f=await fx(); const r=await commit(f,"docs: add Purpose section"); expect(r.commitMessage).toBe("docs: add Purpose section"); expect(await git(f.workspace,["status","--porcelain=v1"])).toBe(""); expect(await readFile(path.join(f.runDir,"commit-result.json"),"utf8")).toContain(r.commitSha);});
 it("commits approved tracked and untracked files and leaves a clean tree",async()=>{const f=await fx({untracked:true}); expect(f.finalResult.finalChangedFiles).toEqual([".rework-ok","a.txt"]); const r=await commit(f,"fix: include untracked"); expect(r.changedFiles).toEqual([".rework-ok","a.txt"]); expect(await git(f.workspace,["show","--name-only","--format=","HEAD"])).toContain(".rework-ok"); expect(await git(f.workspace,["show","--name-only","--format=","HEAD"])).toContain("a.txt"); expect(await git(f.workspace,["status","--porcelain=v1"])).toBe("");});
 it("commits when staged patch order differs from approved workspace diff order",async()=>{const f=await fx({untracked:true}); const approvedDiff=await readFile(path.join(f.runDir,"workspace.diff"),"utf8"); expect(approvedDiff.indexOf("a.txt")).toBeLessThan(approvedDiff.indexOf(".rework-ok")); await git(f.workspace,["add","--all"]); const stagedDiff=await git(f.workspace,["diff","--cached","--binary","HEAD"]); expect(stagedDiff.indexOf(".rework-ok")).toBeLessThan(stagedDiff.indexOf("a.txt")); await git(f.workspace,["reset"]); const r=await commit(f,"fix: tolerate patch order"); expect(r.commitSha).toMatch(/[a-f0-9]{40}/); expect(await git(f.workspace,["status","--porcelain=v1"])).toBe("");});
 it("rejects an approved untracked file whose contents change before commit",async()=>{const f=await fx({untracked:true}); await writeFile(path.join(f.workspace,".rework-ok"),"changed\n"); await expect(commit(f)).rejects.toThrow(/diff changed/);});
 it("rejects a new untracked file created after approval",async()=>{const f=await fx({untracked:true}); await writeFile(path.join(f.workspace,"later.txt"),"later\n"); await expect(commit(f)).rejects.toThrow(/Changed files/);});
 it.each(["REJECT","REQUEST_CHANGES"] as const)("rejects %s",async(decision)=>{const f=await fx({decision}); await expect(commit(f)).rejects.toThrow(/APPROVE/);});
 it("rejects missing human decision via CLI",async()=>{const f=await fx(); await ex("rm",[path.join(f.runDir,"human-decision.json")]); await expect(commitCommand(["--run",f.runId],{runsDir:path.join(f.root,"runs"),cwd:f.root})).rejects.toThrow(/human-decision/);});
 it("rejects non ACCEPTED final status",async()=>{const f=await fx({status:"HUMAN_REQUIRED"}); await expect(commit(f)).rejects.toThrow(/ACCEPTED/);});
 it("rejects missing evidence fingerprint",async()=>{const f=await fx({evidence:false}); await expect(commit(f)).rejects.toThrow(/fingerprints/);});
 it("rejects changed diff after approval",async()=>{const f=await fx(); await writeFile(path.join(f.workspace,"a.txt"),"three\n"); await expect(commit(f)).rejects.toThrow(/diff changed/);});
 it("rejects changed validation report",async()=>{const f=await fx(); await writeFile(path.join(f.runDir,"validation-report.json"),"{}","utf8"); await expect(commit(f)).rejects.toThrow(/fingerprints/);});
 it("rejects changed review report",async()=>{const f=await fx(); await writeFile(path.join(f.runDir,"review-report.json"),"{}","utf8"); await expect(commit(f)).rejects.toThrow(/fingerprints/);});
 it("rejects workspace not top-level",async()=>{const f=await fx({subdir:true}); await mkdir(path.join(f.workspace,"sub")); await expect(commit(f)).rejects.toThrow(/top-level/);});
 it("rejects detached HEAD",async()=>{const f=await fx(); await git(f.workspace,["checkout","--detach"]); await expect(commit(f)).rejects.toThrow(/detached/);});
 it("rejects branch without catos prefix",async()=>{const f=await fx({branch:"feature/run-1"}); await expect(commit(f)).rejects.toThrow(/catos/);});
 it("rejects no changes",async()=>{const f=await fx({change:false}); await expect(commit(f)).rejects.toThrow(/No Git/);});
 it("rejects changed files mismatch",async()=>{const f=await fx(); f.finalResult.finalChangedFiles=["b.txt"]; await expect(commit(f)).rejects.toThrow(/Changed files/);});
 it("resets and rejects when staged content differs from workspace",async()=>{const f=await fx(); await git(f.workspace,["add","--all"]); await writeFile(path.join(f.workspace,"a.txt"),"three\n"); await expect(verifyStagedIndexMatchesWorkspace(f.workspace,f.finalResult.finalChangedFiles)).rejects.toThrow(/Unstaged changes|Staged content/); await git(f.workspace,["reset"]); expect(await git(f.workspace,["diff","--cached","--name-only"])).toBe("");});
 it("rejects a new unapproved staged file",async()=>{const f=await fx(); await writeFile(path.join(f.workspace,"extra.txt"),"extra\n"); await git(f.workspace,["add","--all"]); await expect(verifyStagedIndexMatchesWorkspace(f.workspace,f.finalResult.finalChangedFiles)).rejects.toThrow(/Staged files/); await git(f.workspace,["reset"]); expect(await git(f.workspace,["diff","--cached","--name-only"])).toBe("");});
 it("commits a new binary file",async()=>{const f=await fx({change:false}); await blob(f.workspace,"image.bin",Buffer.from([0,1,2,3,255,0,42])); const state=await collectWorkspaceGitState(f.workspace); await writeFile(path.join(f.runDir,"workspace.diff"),state.diff,"utf8"); f.finalResult.finalChangedFiles=state.changedFiles; f.humanDecision.approvedEvidence={...f.humanDecision.approvedEvidence!,diffSha256:await sha256File(path.join(f.runDir,"workspace.diff"))}; const r=await commit(f,"fix: add binary"); expect(r.changedFiles).toEqual(["image.bin"]); expect(await git(f.workspace,["status","--porcelain=v1"])).toBe("");});
 it("commits a deleted file",async()=>{const f=await fx({change:false}); await ex("rm",[path.join(f.workspace,"a.txt")]); const state=await collectWorkspaceGitState(f.workspace); await writeFile(path.join(f.runDir,"workspace.diff"),state.diff,"utf8"); f.finalResult.finalChangedFiles=state.changedFiles; f.humanDecision.approvedEvidence={...f.humanDecision.approvedEvidence!,diffSha256:await sha256File(path.join(f.runDir,"workspace.diff"))}; const r=await commit(f,"fix: delete file"); expect(r.changedFiles).toEqual(["a.txt"]); expect(await git(f.workspace,["status","--porcelain=v1"])).toBe("");});
 it("second run does not create second commit",async()=>{const f=await fx(); const r=await commit(f); const again=await commit(f); expect(again.commitSha).toBe(r.commitSha);});
 it("existing commit-result with missing commit errors",async()=>{const f=await fx(); await writeFile(path.join(f.runDir,"commit-result.json"),JSON.stringify({schemaVersion:1,runId:f.runId,workspacePath:f.workspace,branch:"catos/run-1",commitSha:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",commitMessage:"x",committedAt:new Date().toISOString(),changedFiles:["a.txt"],parentCommitSha:"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",approvedEvidence:f.humanDecision.approvedEvidence}),"utf8"); await expect(commit(f)).rejects.toThrow(/missing/);});
 it("uses local git identity from config without changing global config",async()=>{const f=await fx(); await commitCommand(["--run",f.runId],{runsDir:path.join(f.root,"runs"),cwd:f.root}); expect(await git(f.workspace,["log","-1","--format=%an <%ae>"])).toBe("Config Name <config@local.invalid>");});
 it("CLI parses --message",async()=>{const f=await fx(); await commitCommand(["--run",f.runId,"--message","custom msg"],{runsDir:path.join(f.root,"runs"),cwd:f.root}); expect(await git(f.workspace,["log","-1","--format=%s"])).toBe("custom msg");});
});
