import { mkdtemp, mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { buildContinuePackage, renderCodexPrompt, renderContinuePackageMarkdown, writeContinuePackage } from "../src/continuePackage.js";
import { artifactRefs, completeAttempt, createSession, createStep, loadStep, recordDecision, startAttempt } from "../src/runs/sessionModel.js";
import { continuePackageCommand } from "../src/cli/continuePackage.js";
import { runStepCommand } from "../src/cli/runStep.js";
import { buildReworkCodexInstruction } from "../src/codingWorker.js";

async function runDir(prefix="catos-continue-") { return mkdtemp(path.join(os.tmpdir(), prefix)); }
async function writeProjectConfig(root:string) { await mkdir(path.join(root,"projects"),{recursive:true}); await writeFile(path.join(root,"projects","demo.yaml"), `project:\n  id: demo\n  name: Demo\n  repoPath: .\n  baseBranch: main\ncommands:\n  typecheck: npm run typecheck\n  test: npm test\n  build: npm run build\nworkflow:\n  maxReworkAttempts: 1\n  createCommit: false\npermissions:\n  allowNetwork: false\n  allowPush: false\n  allowMerge: false\n`, "utf8"); }
async function addReports(dir:string, verdict="ACCEPT", validation="PASS") { await writeFile(path.join(dir,"validation-report.json"), JSON.stringify({schemaVersion:1,status:validation,workspacePath:"/tmp/ws",startedAt:"",finishedAt:"",results:[{name:"typecheck",command:"npm run typecheck",required:true,status:validation,exitCode:validation==="PASS"?0:2,signal:null,stdout:"",stderr:validation==="PASS"?"":"src/foo.ts:42 Type X is not assignable",durationMs:1,timedOut:false}]}, null, 2)); await writeFile(path.join(dir,"review-report.json"), JSON.stringify({schemaVersion:1,verdict,blockingFindings: verdict==="REWORK" ? [{file:"src/foo.ts",message:"Fix foo"}, "Fix foo"] : [], warnings:[{file:"src/bar.ts",message:"Consider bar"}]}, null, 2)); }

describe("Continue Package", () => {
  it("keeps the expanded legacy rework prompt semantically complete", () => {
    const originalTask = "Preserve this original user Task.";
    const prompt = buildReworkCodexInstruction({
      originalTask,
      taskBrief: { objective: "Derived task brief", acceptanceCriteria: ["Acceptance criterion"], nonGoals: [], codexInstruction: "Implement the derived task brief.", riskLevel: "standard" },
      reviewVerdict: "REWORK",
      reworkPackage: { schemaVersion: 1, attempt: 2, originalObjective: "Derived task brief", acceptanceCriteria: ["Acceptance criterion"], blockingFindings: [{ id: "finding-1", title: "Blocking finding", evidence: "Evidence", requiredChange: "Required change" }], preserve: ["Preserve audit artifacts."], mustChange: ["Required change"], mustNotChange: ["Do not create commits."], previousAttemptSummary: "Previous attempt needs rework." },
    });
    expect(prompt).toContain("# Coding rework task");
    expect(prompt).toContain(originalTask);
    expect(prompt).toContain("## Existing derived task brief");
    expect(prompt).toContain("## Review verdict\n\nREWORK");
    expect(prompt).toContain("## Blocking findings");
    expect(prompt).toContain("Required change");
    expect(prompt).toContain("## Acceptance criteria");
    expect(prompt).toContain("Do not create commits, push, merge, or rebase.");
    expect(prompt).toContain("Preserve audit artifacts.");
  });
  it("creates a fresh step package without false previous failures", async () => { const dir=await runDir(); await writeProjectConfig(path.dirname(dir)); const {step}=await createSession({runDir:dir,runId:"run-1",goal:"Goal",branch:"autocodex",request:"Do step"}); const pkg=await buildContinuePackage(dir, new Date("2026-01-01T00:00:00Z"), {cwd:path.dirname(dir)}); expect(pkg.execution.reason).toBe("initial-step"); expect(pkg.previousAttempts).toEqual([]); expect(renderCodexPrompt(pkg)).toContain("No previous attempts"); expect(pkg.currentFindings.blocking).toEqual([]); });
  it("detects validation failure, deduplicates findings and files, and renders stably", async () => { const dir=await runDir(); await writeProjectConfig(path.dirname(dir)); const {step}=await createSession({runDir:dir,runId:"run-2",goal:"Goal",branch:"autocodex"}); await addReports(dir,"ACCEPT","FAIL"); const a=await startAttempt({runDir:dir, step, prompt:"p"}); await completeAttempt({runDir:dir, step, attempt:a, status:"succeeded", changedFiles:["b.ts","a.ts","a.ts"], validationSummary:"FAIL", artifacts:artifactRefs(dir,{validationReportPath:path.join(dir,"validation-report.json"),reviewReportPath:path.join(dir,"review-report.json")})}); const pkg=await buildContinuePackage(dir, new Date("2026-01-01T00:00:00Z"), {cwd:path.dirname(dir)}); expect(pkg.execution.reason).toBe("validation-failure"); expect(pkg.relevantFiles).toEqual(["a.ts","b.ts","src/bar.ts"]); expect(pkg.currentFindings.validationFailures[0]).toContain("typecheck"); expect(renderContinuePackageMarkdown(pkg)).toBe(renderContinuePackageMarkdown(pkg)); });
  it("prioritizes retry, reviewer rework, human changes, and runtime failures", async () => { const dir=await runDir(); await writeProjectConfig(path.dirname(dir)); const {step}=await createSession({runDir:dir,runId:"run-3",goal:"Goal",branch:"autocodex"}); await addReports(dir,"REWORK","PASS"); const a=await startAttempt({runDir:dir, step, prompt:"p"}); await completeAttempt({runDir:dir, step, attempt:a, status:"succeeded", changedFiles:["a.ts"], validationSummary:"PASS", artifacts:artifactRefs(dir,{validationReportPath:path.join(dir,"validation-report.json"),reviewReportPath:path.join(dir,"review-report.json")})}); expect((await buildContinuePackage(dir,new Date(),{cwd:path.dirname(dir)})).execution.reason).toBe("review-rework"); await recordDecision({runDir:dir, step: await loadStep(dir, step.stepId), type:"retry", reason:"Change requested"}); const retryPkg=await buildContinuePackage(dir,new Date(),{cwd:path.dirname(dir)}); expect(retryPkg.execution.reason).toBe("retry"); expect(retryPkg.humanDecision?.requestedChanges).toEqual(["Change requested"]); const b=await startAttempt({runDir:dir, step: await loadStep(dir), prompt:"p2"}); await completeAttempt({runDir:dir, step: await loadStep(dir), attempt:b, status:"timed_out", errorSummary:"timeout"}); expect((await buildContinuePackage(dir,new Date(),{cwd:path.dirname(dir)})).execution.reason).toBe("runtime-failure"); });
  it("limits previous attempts and does not import closed previous step findings", async () => { const dir=await runDir(); await writeProjectConfig(path.dirname(dir)); const {step:first}=await createSession({runDir:dir,runId:"run-4",goal:"Goal",branch:"autocodex"}); await addReports(dir,"REWORK","PASS"); const firstAttempt=await startAttempt({runDir:dir,step:first,prompt:"p"}); await completeAttempt({runDir:dir,step:first,attempt:firstAttempt,status:"succeeded",artifacts:artifactRefs(dir,{reviewReportPath:path.join(dir,"review-report.json")})}); await recordDecision({runDir:dir, step: await loadStep(dir, first.stepId), type:"accept"}); const {step}=await createStep({runDir:dir,title:"Second",request:"Second"}); for(let i=0;i<7;i++){ const a=await startAttempt({runDir:dir, step: await loadStep(dir), prompt:`p${i}`}); await completeAttempt({runDir:dir, step: await loadStep(dir), attempt:a, status:"succeeded", changedFiles:[`f${i}.ts`]}); await recordDecision({runDir:dir, step: await loadStep(dir), type:"retry"}); } const pkg=await buildContinuePackage(dir,new Date(),{cwd:path.dirname(dir)}); expect(pkg.previousAttempts.map(a=>a.order)).toEqual([3,4,5,6,7]); expect(pkg.execution.omittedPreviousAttempts).toBe(2); expect(JSON.stringify(pkg)).not.toContain("Fix foo"); });
  it("redacts secrets in JSON, markdown, and Codex prompt", async () => { const dir=await runDir(); await writeProjectConfig(path.dirname(dir)); const {step}=await createSession({runDir:dir,runId:"run-5",goal:"Goal",branch:"autocodex",request:"Do not leak known-test-secret-value-123 or sk-proj-abcdefghijklmnopqrstuvwxyz123456"}); await writeFile(path.join(dir,"review-report.json"), JSON.stringify({verdict:"REWORK",blockingFindings:["known-test-secret-value-123"]})); const a=await startAttempt({runDir:dir,step,prompt:"p"}); await completeAttempt({runDir:dir,step,attempt:a,status:"failed",errorSummary:"known-test-secret-value-123",artifacts:artifactRefs(dir,{reviewReportPath:path.join(dir,"review-report.json")})}); await recordDecision({runDir:dir, step: await loadStep(dir), type:"retry", reason:"known-test-secret-value-123"}); const out=await writeContinuePackage(dir,new Date("2026-01-01T00:00:00Z"),{cwd:path.dirname(dir)}); const joined=[JSON.stringify(out.package), await readFile(out.markdownPath,"utf8"), await readFile(out.codexPromptPath,"utf8")].join("\n"); expect(joined).not.toContain("known-test-secret-value-123"); expect(joined).not.toContain("sk-proj-"); expect(joined).toContain("[REDACTED]"); });
  it("supports CLI continue-package and fake run-step prompt copy", async () => { const root=await runDir(); const runs=path.join(root,"runs"); const dir=path.join(runs,"run-6"); await mkdir(dir,{recursive:true}); await writeProjectConfig(root); await createSession({runDir:dir,runId:"run-6",goal:"Goal",branch:"autocodex"}); await continuePackageCommand(["--run","run-6"],{runsDir:"runs",cwd:root}); await runStepCommand(["--run","run-6","--fake-child"],{runsDir:"runs",cwd:root}); const step=await loadStep(dir); const copied=await readFile(path.join(dir,"steps",`001-${step.stepId}`,"attempts",(await (await import("node:fs/promises")).readdir(path.join(dir,"steps",`001-${step.stepId}`,"attempts")))[0]!,"prompt.md"),"utf8"); expect(copied).toContain("# Session Goal"); expect(copied).toContain("Do not push."); expect(copied).toContain("Do not merge."); expect(copied).toContain("Do not remove session or audit artifacts."); });
});
