import { describe, expect, test } from "vitest";
import { mkdtemp, mkdir, stat, writeFile } from "node:fs/promises";
import os from "node:os"; import path from "node:path"; import { execFile } from "node:child_process"; import { promisify } from "node:util";
import { cloneGithubRepository, cloneTarget, githubRepos, githubReposFromToken, githubToken, mergeRepositories, normalizeGithubRemote, originHasCredentials, safeSegment, type ExecLike, type FetchLike } from "../src/githubRepositories.js";
import type { RepositoryOption } from "../src/repositoryDiscovery.js";
const exec=promisify(execFile); async function tmp(){return mkdtemp(path.join(os.tmpdir(),"catos-gh-"));} async function repo(r:string,n="repo"){const p=path.join(r,n); await mkdir(p,{recursive:true}); await exec("git",["init","-b","main"],{cwd:p}); await writeFile(path.join(p,"README.md"),"x"); await exec("git",["add","."],{cwd:p}); await exec("git",["-c","user.name=t","-c","user.email=t@e.invalid","commit","-m","init"],{cwd:p}); return p;}
function gh(id:number,name:string,priv=false){return {id,name,full_name:`o/${name}`,clone_url:`https://github.com/o/${name}.git`,ssh_url:`git@github.com:o/${name}.git`,default_branch:"main",private:priv,html_url:`https://github.com/o/${name}`};}
function response(status:number,data:unknown){return {ok:status>=200&&status<300,status,json:async()=>data} as Response;}
describe("GitHub repository helpers",()=>{
 test("GITHUB_TOKEN has priority and GH_TOKEN is fallback",()=>{expect(githubToken({GITHUB_TOKEN:"one",GH_TOKEN:"two"} as NodeJS.ProcessEnv)).toBe("one"); expect(githubToken({GH_TOKEN:"two"} as NodeJS.ProcessEnv)).toBe("two");});
 test("without token and without gh returns unavailable",async()=>{const res=await githubRepos(async()=>{throw new Error("no gh")},{} as NodeJS.ProcessEnv); expect(res.github).toMatchObject({available:false,code:"credentials_unavailable",error:"GitHub repositories unavailable."});});
 test("REST request has safe headers and no token in errors",async()=>{let auth=""; const fetcher:FetchLike=async(_url,init)=>{auth=String(init?.headers && (init.headers as Record<string,string>).Authorization); return response(401,{message:"bad"});}; const res=await githubReposFromToken("secret-token",fetcher); expect(auth).toBe("Bearer secret-token"); expect(JSON.stringify(res.github)).not.toContain("secret-token"); expect(res.github.code).toBe("authentication_failed");});
 test("paginates multiple pages and stops after final short page",async()=>{const urls:string[]=[]; const fetcher:FetchLike=async(url)=>{urls.push(String(url)); return response(200,urls.length===1?Array.from({length:100},(_,i)=>gh(i,`r${i}`)):[gh(101,"last",true)]);}; const res=await githubReposFromToken("t",fetcher); expect(res.repositories).toHaveLength(101); expect(res.repositories.at(-1)?.isPrivate).toBe(true); expect(urls).toHaveLength(2); expect(urls[0]).toContain("page=1"); expect(urls[1]).toContain("page=2");});
 test("maps auth failure, rate limit, network, timeout, malformed JSON, and invalid items",async()=>{await expect(githubReposFromToken("t",async()=>response(401,{}))).resolves.toMatchObject({github:{code:"authentication_failed"}}); await expect(githubReposFromToken("t",async()=>response(403,{}))).resolves.toMatchObject({github:{code:"rate_limited"}}); await expect(githubReposFromToken("t",async()=>{throw new Error("boom")})).resolves.toMatchObject({github:{code:"network_error"}}); await expect(githubReposFromToken("t",async()=>({ok:true,status:200,json:async()=>{throw new Error("bad")}} as Response))).resolves.toMatchObject({github:{code:"invalid_response"}}); await expect(githubReposFromToken("t",async()=>response(200,[{id:"bad"}]))).resolves.toMatchObject({github:{code:"invalid_response"}});});
 test("local discovery can merge when API failed",async()=>{const r=await tmp(); const p=await repo(r,"local"); const local:RepositoryOption[]=[{id:p,source:"local",name:"local",path:p,localPath:p,isAvailableLocally:true}]; await expect(mergeRepositories(local,[])).resolves.toHaveLength(1);});
 test("normalizes HTTPS and SSH remotes",()=>{expect(normalizeGithubRemote("https://github.com/Owner/Repo.git")).toBe("owner/repo"); expect(normalizeGithubRemote("git@github.com:Owner/Repo.git")).toBe("owner/repo"); expect(normalizeGithubRemote("ssh://git@github.com/Owner/Repo.git")).toBe("owner/repo");});
 test("deduplicates local GitHub origins and preserves order",async()=>{const r=await tmp(); const p=await repo(r,"local"); await exec("git",["-C",p,"remote","add","origin","git@github.com:O/Local.git"]); const local:RepositoryOption[]=[{id:p,source:"local",name:"local",path:p,localPath:p,isAvailableLocally:true}]; const merged=await mergeRepositories(local,[{...gh(1,"local"),fullName:"o/local"},{...gh(2,"remote"),fullName:"o/remote"}]); expect(merged.map(x=>x.id)).toEqual([p,"github:o/remote"]); expect(merged[0]?.fullName).toBe("o/local");});
 test("clone target stays under managed root and rejects traversal",()=>{const root=path.join(os.tmpdir(),"managed"); expect(cloneTarget("owner/repo",root)).toBe(path.join(root,"owner","repo")); expect(()=>cloneTarget("../repo",root)).toThrow(); expect(()=>safeSegment("bad/name")).toThrow();});
 test("credential detector catches tokens and userinfo",()=>{expect(originHasCredentials("https://user:pass@github.com/o/r.git")).toBe(true); expect(originHasCredentials("https://oauth2:token@github.com/o/r.git")).toBe(true); expect(originHasCredentials("https://github.com/o/r.git")).toBe(false);});
 test("clone uses GIT_ASKPASS, clean URL, and removes helper on success",async()=>{const root=await tmp(); process.env.CATOS_REPOSITORIES_ROOT=root; const calls:Record<string,unknown>[]=[]; let helper=""; const fake:ExecLike=async(file,args,opts={})=>{calls.push({file,args,opts}); if(args[0]==="clone"){expect(args[1]).toBe("https://github.com/o/private.git"); expect(String(args[1])).not.toContain("token"); helper=String((opts.env as Record<string,string>).GIT_ASKPASS); throw new Error("clone failed");} if(args.includes("remote")&&args.includes("get-url")) return {stdout:"https://github.com/o/private.git"}; return {stdout:""};}; await expect(cloneGithubRepository("github:o/private",[{id:"github:o/private",source:"github",name:"o/private",fullName:"o/private",cloneUrl:"https://github.com/o/private.git",isAvailableLocally:false}],fake,{GITHUB_TOKEN:"token"} as NodeJS.ProcessEnv)).rejects.toThrow("clone failed"); await expect(stat(helper)).rejects.toThrow(); delete process.env.CATOS_REPOSITORIES_ROOT;});
});
