import { describe, expect, test } from "vitest";
import { mkdtemp, mkdir, stat, writeFile } from "node:fs/promises";
import os from "node:os"; import path from "node:path"; import { execFile } from "node:child_process"; import { promisify } from "node:util";
import { cloneGithubRepository, cloneTarget, githubRepos, githubReposFromToken, githubToken, mergeRepositories, normalizeGithubRemote, originHasCredentials, safeSegment, type ExecLike, type FetchLike, type GithubRepo } from "../src/githubRepositories.js";
import { discoverRepositories } from "../src/repositoryDiscovery.js";
import { listBranches, listRepositories } from "../src/uiApi.js";
import { findRepository } from "../src/ui/repositorySelection.js";
import type { RepositoryOption } from "../src/repositoryDiscovery.js";
const exec=promisify(execFile); async function tmp(){return mkdtemp(path.join(os.tmpdir(),"catos-gh-"));} async function repo(r:string,n="repo"){const p=path.join(r,n); await mkdir(p,{recursive:true}); await exec("git",["init","-b","main"],{cwd:p}); await writeFile(path.join(p,"README.md"),"x"); await exec("git",["add","."],{cwd:p}); await exec("git",["-c","user.name=t","-c","user.email=t@e.invalid","commit","-m","init"],{cwd:p}); return p;}
function rawGithubApiRepo(id:number,name:string,priv=false){return {id,name,full_name:`o/${name}`,clone_url:`https://github.com/o/${name}.git`,ssh_url:`git@github.com:o/${name}.git`,default_branch:"main",private:priv,html_url:`https://github.com/o/${name}`};}
function normalizedGithubRepo(id:number,name:string,fullName=`o/${name}`):GithubRepo{return {id,name,fullName,cloneUrl:`https://github.com/${fullName}.git`,defaultBranch:"main",isPrivate:false};}
function response(status:number,data:unknown){return {ok:status>=200&&status<300,status,headers:new Headers(),json:async()=>data} as unknown as Response;}
describe("GitHub repository helpers",()=>{
 test("GITHUB_TOKEN has priority and GH_TOKEN is fallback",()=>{expect(githubToken({GITHUB_TOKEN:"one",GH_TOKEN:"two"} as NodeJS.ProcessEnv)).toBe("one"); expect(githubToken({GH_TOKEN:"two"} as NodeJS.ProcessEnv)).toBe("two");});
 test("without token and without gh returns unavailable",async()=>{const res=await githubRepos(async()=>{throw new Error("no gh")},{} as NodeJS.ProcessEnv); expect(res.github).toMatchObject({available:false,code:"credentials_unavailable",error:"GitHub repositories unavailable."});});
 test("REST request has safe headers and no token in errors",async()=>{let auth=""; const fetcher:FetchLike=async(_url,init)=>{auth=String(init?.headers && (init.headers as Record<string,string>).Authorization); return response(401,{message:"bad"});}; const res=await githubReposFromToken("secret-token",fetcher); expect(auth).toBe("Bearer secret-token"); expect(JSON.stringify(res.github)).not.toContain("secret-token"); expect(res.github.code).toBe("authentication_failed");});
 test("paginates multiple pages and stops after final short page",async()=>{const urls:string[]=[]; const fetcher:FetchLike=async(url)=>{urls.push(String(url)); return response(200,urls.length===1?Array.from({length:100},(_,i)=>rawGithubApiRepo(i,`r${i}`)):[rawGithubApiRepo(101,"last",true)]);}; const res=await githubReposFromToken("t",fetcher); expect(res.repositories).toHaveLength(101); expect(res.repositories.at(-1)?.isPrivate).toBe(true); expect(urls).toHaveLength(2); expect(urls[0]).toContain("page=1"); expect(urls[1]).toContain("page=2");});
 test("maps auth failure, rate limit, network, timeout, malformed JSON, and invalid items",async()=>{await expect(githubReposFromToken("t",async()=>response(401,{}))).resolves.toMatchObject({github:{code:"authentication_failed"}}); await expect(githubReposFromToken("t",async()=>response(403,{}))).resolves.toMatchObject({github:{code:"rate_limited"}}); await expect(githubReposFromToken("t",async()=>{throw new Error("boom")})).resolves.toMatchObject({github:{code:"network_error"}}); await expect(githubReposFromToken("t",async()=>({ok:true,status:200,headers:new Headers(),json:async()=>{throw new Error("bad")}} as unknown as Response))).resolves.toMatchObject({github:{code:"invalid_response"}}); await expect(githubReposFromToken("t",async()=>response(200,[{id:"bad"}]))).resolves.toMatchObject({github:{code:"invalid_response"}});});
 test("local discovery can merge when API failed",async()=>{const r=await tmp(); const p=await repo(r,"local"); const local:RepositoryOption[]=[{id:p,source:"local",name:"local",path:p,localPath:p,isAvailableLocally:true}]; await expect(mergeRepositories(local,[])).resolves.toHaveLength(1);});
 test("normalizes HTTPS and SSH remotes",()=>{expect(normalizeGithubRemote("https://github.com/Owner/Repo.git")).toBe("owner/repo"); expect(normalizeGithubRemote("git@github.com:Owner/Repo.git")).toBe("owner/repo"); expect(normalizeGithubRemote("ssh://git@github.com/Owner/Repo.git")).toBe("owner/repo");});
 test("deduplicates local GitHub origins and preserves order",async()=>{const r=await tmp(); const p=await repo(r,"local"); await exec("git",["-C",p,"remote","add","origin","git@github.com:O/Local.git"]); const local:RepositoryOption[]=[{id:p,source:"local",name:"local",path:p,localPath:p,isAvailableLocally:true}]; const merged=await mergeRepositories(local,[normalizedGithubRepo(1,"local","o/local"),normalizedGithubRepo(2,"remote","o/remote")]); expect(merged.map(x=>x.id)).toEqual([p,"github:o/remote"]); expect(merged[0]?.fullName).toBe("o/local");});
 test("clone target stays under managed root and rejects traversal",()=>{const root=path.join(os.tmpdir(),"managed"); expect(cloneTarget("owner/repo","feature/test",root)).toBe(path.join(root,"Cloned","owner","repo","feature","test")); expect(()=>cloneTarget("../repo","main",root)).toThrow(); expect(()=>cloneTarget("owner/repo","../bad",root)).toThrow(); expect(()=>safeSegment("bad/name")).toThrow();});
 test("credential detector catches tokens and userinfo",()=>{expect(originHasCredentials("https://user:pass@github.com/o/r.git")).toBe(true); expect(originHasCredentials("https://oauth2:token@github.com/o/r.git")).toBe(true); expect(originHasCredentials("https://github.com/o/r.git")).toBe(false);});
 test("integration clone workflow uses a real local bare repository without GitHub network",async()=>{
  const r=await tmp(); const source=await repo(r,"source"); await exec("git",["-C",source,"checkout","-b","feature/local-clone"]); await writeFile(path.join(source,"feature.txt"),"feature"); await exec("git",["-C",source,"add","."]); await exec("git",["-C",source,"-c","user.name=t","-c","user.email=t@e.invalid","commit","-m","feature"]);
  const bare=path.join(r,"source.git"); await exec("git",["clone","--bare",source,bare]);
  const managedRoot=path.join(r,"managed"); const cwd=path.join(r,"cwd"); await mkdir(cwd,{recursive:true}); await writeFile(path.join(cwd,"catos.config.yaml"),`repositoryRoots:
  - ${managedRoot}
`);
  const env={CATOS_REPOSITORIES_ROOT:managedRoot} as NodeJS.ProcessEnv;
  const githubRepo=normalizedGithubRepo(42,"repo","owner/repo"); githubRepo.cloneUrl=`file://${bare}`;
  const githubProvider=async()=>({repositories:[githubRepo],github:{available:true,error:null}});
  const before=await listRepositories({cwd,env,githubProvider});
  const remoteBefore=before.repositories.filter(repo=>repo.fullName?.toLowerCase()==="owner/repo");
  expect(remoteBefore).toHaveLength(1); expect(remoteBefore[0]).toMatchObject({id:"github:owner/repo",source:"github",fullName:"owner/repo",isAvailableLocally:false});
   const cloned=await cloneGithubRepository("github:owner/repo","feature/local-clone",before.repositories,undefined,env);
   const expectedTarget=path.join(managedRoot,"Cloned","owner","repo","feature","local-clone");
   expect(cloned.repository.localPath).toBe(expectedTarget); expect(cloned.repository.path).toBe(expectedTarget); expect(cloned.repository.isAvailableLocally).toBe(true); expect(cloned.repository.currentBranch).toBe("feature/local-clone"); expect(cloned.repository.branches?.map(b=>b.name)).toContain("feature/local-clone"); expect(cloned.branch).toBe("feature/local-clone"); expect(cloned.headCommit).toMatch(/^[0-9a-f]{40}$/);
   await expect(exec("git",["-C",expectedTarget,"rev-parse","--is-inside-work-tree"])).resolves.toMatchObject({stdout:"true\n"});
   await expect(exec("git",["-C",expectedTarget,"rev-parse","--verify","feature/local-clone"])).resolves.toBeTruthy();
   const origin=(await exec("git",["-C",expectedTarget,"remote","get-url","origin"])).stdout.trim(); expect(origin).toBe(`file://${bare}`); expect(originHasCredentials(origin)).toBe(false);
   const discovered=await discoverRepositories([managedRoot],cwd,3,env); expect(discovered.map(repo=>repo.path)).toContain(expectedTarget);
   const refreshed=await listRepositories({cwd,env,githubProvider}); const matchingAfter=refreshed.repositories.filter(repo=>repo.fullName?.toLowerCase()==="owner/repo"); expect(matchingAfter).toHaveLength(1); expect(matchingAfter[0]).toMatchObject({source:"local",fullName:"owner/repo",localPath:expectedTarget,isAvailableLocally:true,currentBranch:"feature/local-clone"});
   const branches=await listBranches(expectedTarget); expect(branches.branches.map(b=>b.name)).toContain("feature/local-clone");
   const matched=findRepository(refreshed.repositories,cloned.repository); expect(matched?.localPath).toBe(expectedTarget); expect(matched?.id).not.toBe(process.cwd()); expect(matchingAfter[0]?.localPath).toBe(expectedTarget);
 });

 test("ambient real managed repos are ignored when test context provides a temporary managed root",async()=>{
  const r=await tmp(); const cwd=path.join(r,"cwd"); const managedRoot=path.join(r,"managed"); await mkdir(cwd,{recursive:true}); await mkdir(managedRoot,{recursive:true}); await writeFile(path.join(cwd,"catos.config.yaml"),`repositoryRoots:
  - ${managedRoot}
`);
  const previousRoot=process.env.CATOS_REPOSITORIES_ROOT; const ambientRoot=path.join(r,"ambient"); const ambientRepo=await repo(path.join(ambientRoot,"owner"),"ambient"); process.env.CATOS_REPOSITORIES_ROOT=ambientRoot;
  try{ const res=await listRepositories({cwd,env:{CATOS_REPOSITORIES_ROOT:managedRoot} as NodeJS.ProcessEnv,githubProvider:async()=>({repositories:[],github:{available:false,error:"GitHub repositories unavailable.",code:"credentials_unavailable"}})}); expect(res.repositories.map(repo=>repo.localPath ?? repo.path)).not.toContain(ambientRepo); expect(res.repositories).toEqual([]); }
  finally{ if(previousRoot===undefined) delete process.env.CATOS_REPOSITORIES_ROOT; else process.env.CATOS_REPOSITORIES_ROOT=previousRoot; }
 });
 test("clone uses GIT_ASKPASS, clean URL, and removes helper on success",async()=>{const root=await tmp(); process.env.CATOS_REPOSITORIES_ROOT=root; const calls:Record<string,unknown>[]=[]; let helper=""; const fake:ExecLike=async(file,args,opts={})=>{calls.push({file,args,opts}); if(args[0]==="clone"){expect(args).toContain("https://github.com/o/private.git"); expect(args).toContain("--branch"); expect(args).toContain("--single-branch"); expect(args).toContain("--depth"); expect(args).toContain("1"); expect(JSON.stringify(args)).not.toContain("token"); helper=String((opts.env as Record<string,string>).GIT_ASKPASS); throw new Error("clone failed");} if(args.includes("remote")&&args.includes("get-url")) return {stdout:"https://github.com/o/private.git"}; return {stdout:""};}; await expect(cloneGithubRepository("github:o/private","main",[{id:"github:o/private",source:"github",name:"o/private",fullName:"o/private",cloneUrl:"https://github.com/o/private.git",isAvailableLocally:false}],fake,{GITHUB_TOKEN:"token",CATOS_REPOSITORIES_ROOT:root} as NodeJS.ProcessEnv)).rejects.toThrow("Git clone failed"); await expect(stat(helper)).rejects.toThrow(); delete process.env.CATOS_REPOSITORIES_ROOT;});
});
