import { describe, expect, test } from "vitest";
import { mkdtemp, mkdir, symlink, writeFile } from "node:fs/promises";
import os from "node:os"; import path from "node:path"; import { execFile } from "node:child_process"; import { promisify } from "node:util";
import { defaultBaseBranch, defaultPrTarget, listRepositoryBranches, scanRepositories, validateManualRepository } from "../src/repositoryDiscovery.js";
const exec=promisify(execFile); async function repo(root:string,name="repo"){const p=path.join(root,name); await mkdir(p,{recursive:true}); await exec("git",["init","-b","main"],{cwd:p}); await writeFile(path.join(p,"README.md"),"x"); await exec("git",["add","."] ,{cwd:p}); await exec("git",["-c","user.name=t","-c","user.email=t@e.invalid","commit","-m","init"],{cwd:p}); return p;} async function tmp(){return mkdtemp(path.join(os.tmpdir(),"catos-repo-"));}
describe("repository discovery",()=>{
 test("finds one and multiple Git repositories but not plain dirs",async()=>{const r=await tmp(); const a=await repo(r,"a"); const b=await repo(r,"b"); await mkdir(path.join(r,"plain")); const found=await scanRepositories([r]); expect(found.map(x=>x.path).sort()).toEqual([a,b].sort());});
 test("deduplicates symlinks and ignores node_modules/runs/workspaces",async()=>{const r=await tmp(); const a=await repo(r,"a"); await symlink(a,path.join(r,"link")); await mkdir(path.join(r,"node_modules","x"),{recursive:true}); await repo(path.join(r,"node_modules"),"hidden"); await mkdir(path.join(r,"runs","x"),{recursive:true}); const found=await scanRepositories([r]); expect(found).toHaveLength(1); expect(found[0]!.path).toBe(a);});
 test("limits depth and survives unreadable/missing dirs",async()=>{const r=await tmp(); await repo(path.join(r,"one","two","three"),"deep"); await expect(scanRepositories([r,path.join(r,"missing")],2)).resolves.toEqual([]);});
 test("manual repo and branch helpers",async()=>{const r=await tmp(); const p=await repo(r); await exec("git",["checkout","-b","feature/export"],{cwd:p}); const manual=await validateManualRepository(p); expect(manual.path).toBe(p); const branches=await listRepositoryBranches(p); expect(branches.find(b=>b.name==="feature/export")?.current).toBe(true); expect(defaultBaseBranch(branches)).toBe("feature/export"); expect(defaultPrTarget("main","old",false)).toBe("main"); expect(defaultPrTarget("main","old",true)).toBe("old");});
});
