import { expect, test } from "vitest";
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { buildUiSystemState, buildUiTimeline } from "../src/uiViewModel.js";
import { writeSessionReport } from "../src/finalExport.js";
import { writeFinalResult } from "../src/reworkLoop.js";
import { readRunOutput, resolveRunDownload } from "../src/uiApi.js";

async function fixture(){ const root=await mkdtemp(path.join(os.tmpdir(),"catos-ui-contract-")); const runDir=path.join(root,"runs","run-1"); const ws=path.join(root,"ws"); await mkdir(path.join(ws,"docs"),{recursive:true}); await mkdir(path.join(runDir,"steps","001-step","attempts","001-attempt"),{recursive:true}); return {root,runDir,ws,attemptDir:path.join(runDir,"steps","001-step","attempts","001-attempt")}; }
async function writeBase(f:Awaited<ReturnType<typeof fixture>>, verdict="ACCEPT", validation="PASS", attemptStatus="succeeded"){ await writeFile(path.join(f.ws,"docs","AUTOCODEX_TEST.md"),"hello\n"); await writeFile(path.join(f.runDir,"input.json"),JSON.stringify({runId:"run-1",repositoryPath:f.ws,baseBranch:"autocodex",goal:"create docs/AUTOCODEX_TEST.md"})); await writeFile(path.join(f.runDir,"session.json"),JSON.stringify({runId:"run-1",sessionId:"run-1",goal:"create docs/AUTOCODEX_TEST.md",status:"running",branch:"autocodex",workspacePath:f.ws,createdAt:"2026-07-14T00:00:00.000Z",updatedAt:"2026-07-14T00:00:01.000Z",activeStepId:"step"})); await writeFile(path.join(f.attemptDir,"attempt.json"),JSON.stringify({attemptId:"attempt",stepId:"step",order:1,status:attemptStatus,prompt:"p",startedAt:"2026-07-14T00:00:00.000Z",completedAt:"2026-07-14T00:00:01.234Z",changedFiles:["docs/AUTOCODEX_TEST.md"],artifacts:{validationReportPath:path.join(f.attemptDir,"validation-report.json"),reviewReportPath:path.join(f.attemptDir,"review-report.json")}})); await writeFile(path.join(f.attemptDir,"validation-report.json"),JSON.stringify({status:validation,results:[]})); await writeFile(path.join(f.attemptDir,"review-report.json"),JSON.stringify({verdict,summary: verdict==="REWORK"?"Validation failed: docs/AUTOCODEX_TEST.md was not found.":"accepted",blockingFindings: verdict==="REWORK"?[{title:"missing",requiredChange:"create file"}]:[]})); }

for (const [name,status] of [["completed","ACCEPTED"],["failed","REWORK_LIMIT_REACHED"]] as const) {
  test(`FINAL_REPORT.md is generated for ${name} runs`, async()=>{ const f=await fixture(); await writeBase(f,status==="ACCEPTED"?"ACCEPT":"REWORK",status==="ACCEPTED"?"PASS":"FAIL"); await writeFinalResult(f.runDir,{schemaVersion:1,runId:"run-1",status,terminalMessage:status==="ACCEPTED"?"TASK COMPLETE":"TASK FAILED",error:status==="ACCEPTED"?null:{code:"REVIEW_REWORK_REQUIRED",message:"Expected file was not found."},finalReviewVerdict:status==="ACCEPTED"?"ACCEPT":"REWORK",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:["docs/AUTOCODEX_TEST.md"],finalValidationStatus:status==="ACCEPTED"?"PASS":"FAIL",finalReviewReportPath:path.join(f.attemptDir,"review-report.json"),outputs:[]}); await expect(readFile(path.join(f.runDir,"FINAL_REPORT.md"),"utf8")).resolves.toContain("# AutoCodex Final Report"); const s=await buildUiSystemState(f.runDir); expect(s.outputs).toEqual([{label:"FINAL_REPORT.md",path:"FINAL_REPORT.md",readable:true,downloadable:true}]); expect(s.finalReport.label).toBe("FINAL_REPORT.md"); });
}

test("FINAL_REPORT.md is generated for stopped runs", async()=>{ const f=await fixture(); await writeBase(f); await writeFile(path.join(f.runDir,".ui-stopped"),"stop"); const report=await writeSessionReport(f.runDir); expect(path.basename(report)).toBe("FINAL_REPORT.md"); await expect(readFile(report,"utf8")).resolves.toContain("- status: stopped"); });

test("timeline exposes exactly CODEX, VALIDATION, REVIEW with deterministic result files", async()=>{ const f=await fixture(); await writeBase(f,"REWORK","FAIL"); await writeSessionReport(f.runDir); const rows=await buildUiTimeline(f.runDir); expect(rows.map(r=>r.name)).toEqual(["CODEX","VALIDATION","REVIEW"]); expect(rows.map(r=>r.resultFile?.label)).toEqual(["01_CODEX.md","02_VALIDATION.md","03_REVIEW.md"]); for (const row of rows) await expect(readFile(path.join(f.runDir,row.resultFile!.path),"utf8")).resolves.toContain(`# ${row.name} Result`); expect(rows.find(r=>r.name==="REVIEW")?.status).toBe("rework"); });

test("safe final report and step output access rejects traversal and preserves download filename", async()=>{ const f=await fixture(); await writeBase(f); await writeFinalResult(f.runDir,{schemaVersion:1,runId:"run-1",status:"ACCEPTED",terminalMessage:"TASK COMPLETE",error:null,finalReviewVerdict:"ACCEPT",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:[],finalValidationStatus:"PASS",finalReviewReportPath:path.join(f.attemptDir,"review-report.json"),outputs:[]}); await expect(readRunOutput("run-1","../secret",{cwd:f.root,runsDir:path.join(f.root,"runs")})).rejects.toThrow("Path traversal rejected"); await expect(readRunOutput("run-1","01_CODEX.md",{cwd:f.root,runsDir:path.join(f.root,"runs")})).resolves.toMatchObject({path:"01_CODEX.md"}); await expect(resolveRunDownload("run-1","FINAL_REPORT.md",{cwd:f.root,runsDir:path.join(f.root,"runs")})).resolves.toMatchObject({filename:"FINAL_REPORT.md"}); });

test("frontend MVP removes obsolete RUN and OUTPUT elements", async()=>{ const app = await readFile(new URL("../src/ui/app.js", import.meta.url), "utf8"); const html = await readFile(new URL("../src/ui/index.html", import.meta.url), "utf8"); const css = await readFile(new URL("../src/ui/app.css", import.meta.url), "utf8"); expect(html).not.toContain("technicalDetails"); expect(html).not.toContain("errorPanel"); expect(html).not.toContain("outputList"); expect(html).not.toContain("viewerPath"); expect(html).not.toContain("Technical details"); expect(html).not.toContain("session report"); expect(html).toContain("FINAL_REPORT.md"); expect(app).not.toContain("$('system')"); expect(app).not.toContain("viewerPath"); expect(app).not.toContain("outputList"); expect(app).toContain("data-step-path"); expect(css).toContain("grid-template-columns:24px minmax(100px,1fr) 100px 64px 56px"); });

test("step COPY is disabled when step result unavailable and enabled with availability class when readable", async()=>{ const source = await readFile(new URL("../src/ui/app.js", import.meta.url), "utf8"); expect(source).toContain("const available=!!rf?.exists&&!!rf?.readable&&!!rf?.path"); expect(source).toContain("copy-available"); expect(source).toContain("Result file unavailable"); });

test("RUN row markup contains only index name status duration and COPY", async()=>{ const source = await readFile(new URL("../src/ui/app.js", import.meta.url), "utf8"); expect(source).toContain('class="timeline-index"'); expect(source).toContain('class="timeline-step"'); expect(source).toContain('class="timeline-status"'); expect(source).toContain('class="timeline-time"'); expect(source).toContain("copyButtonClass('step-copy',available)"); expect(source).not.toContain('timeline-message'); expect(source).not.toContain('${esc(r.message)}'); });

test("OUTPUT panel exposes exactly FINAL_REPORT.md and no selector path or preview", async()=>{ const html = await readFile(new URL("../src/ui/index.html", import.meta.url), "utf8"); expect(html).toContain('<h2>OUTPUT</h2>'); expect(html).toContain('<strong id="viewerTitle">FINAL_REPORT.md</strong>'); expect(html).toContain('>COPY</button>'); expect(html).toContain('>DOWNLOAD</button>'); expect(html).not.toContain('id="outputList"'); expect(html).not.toContain('output-tabs'); expect(html).not.toContain('output-path'); expect(html).not.toContain('<pre'); });


test("terminal step resultFile availability is checked from files, not status", async()=>{ const f=await fixture(); await writeBase(f,"REWORK","FAIL"); await writeSessionReport(f.runDir); await rm(path.join(f.runDir,"02_VALIDATION.md")); const s=await buildUiSystemState(f.runDir); expect(s.steps.map(r=>r.resultFile)).toEqual([{label:"01_CODEX.md",path:"01_CODEX.md",exists:true,readable:true},{label:"02_VALIDATION.md",path:"02_VALIDATION.md",exists:false,readable:false},{label:"03_REVIEW.md",path:"03_REVIEW.md",exists:true,readable:true}]); });

test("frontend COPY messages and fallback distinguish file load and clipboard failures", async()=>{ const source=await readFile(new URL("../src/ui/app.js", import.meta.url),"utf8"); expect(source).toContain("Could not load result file."); expect(source).toContain("Clipboard unavailable."); expect(source).toContain("Copied."); expect(source).toContain("document.createElement('textarea')"); expect(source).toContain("document.execCommand('copy')"); expect(source).toContain("copy-success"); expect(source).toContain("copy-error"); });

test("FINAL_REPORT.md availability controls COPY and DOWNLOAD from readability and downloadability", async()=>{ const source=await readFile(new URL("../src/ui/app.js", import.meta.url),"utf8"); expect(source).toContain("$('copy').disabled=!copyAvailable"); expect(source).toContain("$('download').disabled=!report.downloadable"); const f=await fixture(); await writeBase(f); await mkdir(path.join(f.runDir,"FINAL_REPORT.md"),{recursive:true}); const s=await buildUiSystemState(f.runDir); expect(s.finalReport).toEqual({label:"FINAL_REPORT.md",path:"FINAL_REPORT.md",readable:false,downloadable:false}); });
