import { expect, test } from "vitest";
import { mkdtemp, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { buildUiSystemState, buildUiTimeline } from "../src/uiViewModel.js";
import { writeSessionReport } from "../src/finalExport.js";
import { writeFinalResult } from "../src/reworkLoop.js";
import { readRunOutput, resolveRunDownload } from "../src/uiApi.js";

async function fixture(){ const root=await mkdtemp(path.join(os.tmpdir(),"catos-ui-contract-")); const runDir=path.join(root,"runs","run-1"); const ws=path.join(root,"ws"); await mkdir(path.join(ws,"docs"),{recursive:true}); await mkdir(path.join(runDir,"steps","001-step","attempts","001-attempt"),{recursive:true}); return {root,runDir,ws,attemptDir:path.join(runDir,"steps","001-step","attempts","001-attempt")}; }

async function writeBase(f:Awaited<ReturnType<typeof fixture>>, verdict="ACCEPT", validation="PASS"){
  await writeFile(path.join(f.ws,"docs","AUTOCODEX_TEST.md"),"hello\n");
  await writeFile(path.join(f.runDir,"session.json"),JSON.stringify({sessionId:"run-1",goal:"create docs/AUTOCODEX_TEST.md",status:"running",branch:"autocodex",workspacePath:f.ws,createdAt:"2026-07-14T00:00:00.000Z",updatedAt:"2026-07-14T00:00:01.000Z",activeStepId:"step"}));
  await writeFile(path.join(f.attemptDir,"attempt.json"),JSON.stringify({attemptId:"attempt",stepId:"step",order:1,status:"succeeded",prompt:"p",startedAt:"2026-07-14T00:00:00.000Z",completedAt:"2026-07-14T00:00:01.234Z",changedFiles:["docs/AUTOCODEX_TEST.md"],artifacts:{validationReportPath:path.join(f.attemptDir,"validation-report.json"),reviewReportPath:path.join(f.attemptDir,"review-report.json")}}));
  await writeFile(path.join(f.attemptDir,"validation-report.json"),JSON.stringify({status:validation,results:[]}));
  await writeFile(path.join(f.attemptDir,"review-report.json"),JSON.stringify({verdict,summary: verdict==="REWORK"?"Validation failed: docs/AUTOCODEX_TEST.md was not found.":"accepted",blockingFindings: verdict==="REWORK"?[{title:"missing",requiredChange:"create file"}]:[]}));
}

test("discovers user-created docs/AUTOCODEX_TEST.md and does not substitute internal report", async()=>{ const f=await fixture(); await writeBase(f); await writeFile(path.join(f.runDir,"final-result.json"),JSON.stringify({schemaVersion:1,runId:"run-1",status:"ACCEPTED",finalReviewVerdict:"ACCEPT",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:["docs/AUTOCODEX_TEST.md"],finalValidationStatus:"PASS",finalReviewReportPath:path.join(f.attemptDir,"review-report.json")})); const s=await buildUiSystemState(f.runDir); expect(s.changedFiles[0]).toMatchObject({path:"docs/AUTOCODEX_TEST.md",exists:true}); expect(s.outputs.map(o=>o.path)).toEqual(["docs/AUTOCODEX_TEST.md"]); expect(s.outputs.map(o=>o.path)).not.toContain("AUTOCODEX_SESSION_REPORT.md"); expect(s.terminalMessage).toBe("TASK COMPLETE"); });

test("missing optional internal report does not fail and failed validation has structured error and rework reason", async()=>{ const f=await fixture(); await writeBase(f,"REWORK","FAIL"); await writeFile(path.join(f.runDir,"final-result.json"),JSON.stringify({schemaVersion:1,runId:"run-1",status:"REWORK_LIMIT_REACHED",finalReviewVerdict:"REWORK",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:["docs/AUTOCODEX_TEST.md"],finalValidationStatus:"FAIL",finalReviewReportPath:path.join(f.attemptDir,"review-report.json")})); const s=await buildUiSystemState(f.runDir); expect(s.error).toMatchObject({code:"attempt_exhaustion"}); expect(s.error?.stepId).toContain("review"); const rows=await buildUiTimeline(f.runDir); expect(rows.map(r=>r.label)).toEqual(["Run Codex task","Run validation","Review changes"]); expect(rows.some(r=>r.label==="step")).toBe(false); expect(rows.find(r=>r.status==="rework")?.message).toContain("docs/AUTOCODEX_TEST.md"); });


test("every executed step writes readable result artifact and rework reason", async()=>{ const f=await fixture(); await writeBase(f,"REWORK","FAIL"); const report=await writeSessionReport(f.runDir); await expect(stat(report)).resolves.toBeTruthy(); const rows=await buildUiTimeline(f.runDir); for(const row of rows){ expect(row.artifactPath).toMatch(/result\.md$/); await expect(readFile(path.join(f.runDir,row.artifactPath!),"utf8")).resolves.toContain("# Step Result:"); } const review=rows.find(r=>r.status==="rework")!; expect(review.message).toBeTruthy(); const reviewResult=await readFile(path.join(f.runDir,review.artifactPath!),"utf8"); expect(reviewResult).toContain("why rework was requested"); expect(reviewResult).toContain("review decision"); });

test("final session report is generated on completed and failed finalization", async()=>{ for(const status of ["ACCEPTED","REWORK_LIMIT_REACHED"] as const){ const f=await fixture(); await writeBase(f,status==="ACCEPTED"?"ACCEPT":"REWORK",status==="ACCEPTED"?"PASS":"FAIL"); await writeFinalResult(f.runDir,{schemaVersion:1,runId:"run-1",status,terminalMessage:status==="ACCEPTED"?"TASK COMPLETE":"TASK FAILED",error:status==="ACCEPTED"?null:{code:"REVIEW_REWORK_REQUIRED",message:"Expected file was not found."},finalReviewVerdict:status==="ACCEPTED"?"ACCEPT":"REWORK",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:["docs/AUTOCODEX_TEST.md"],finalValidationStatus:status==="ACCEPTED"?"PASS":"FAIL",finalReviewReportPath:path.join(f.attemptDir,"review-report.json"),outputs:[{label:"AUTOCODEX_TEST.md",path:"docs/AUTOCODEX_TEST.md",type:"file",contentAvailable:true}]}); await expect(readFile(path.join(f.runDir,"AUTOCODEX_SESSION_REPORT.md"),"utf8")).resolves.toContain("# AutoCodex Session Report"); const final=JSON.parse(await readFile(path.join(f.runDir,"final-result.json"),"utf8")); expect(final.runArtifacts.some((a:any)=>a.kind==="session-report")).toBe(true); expect(final.outputs.every((o:any)=>!o.kind)).toBe(true); } });

test("final session report is generated on stopped runs", async()=>{ const f=await fixture(); await writeBase(f); await writeFile(path.join(f.runDir,".ui-stopped"),"stop"); const report=await writeSessionReport(f.runDir); await expect(readFile(report,"utf8")).resolves.toContain("- status: stopped"); });

test("user outputs stay first and session report does not replace them", async()=>{ const f=await fixture(); await writeBase(f); await writeFinalResult(f.runDir,{schemaVersion:1,runId:"run-1",status:"ACCEPTED",terminalMessage:"TASK COMPLETE",error:null,finalReviewVerdict:"ACCEPT",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:["docs/AUTOCODEX_TEST.md"],finalValidationStatus:"PASS",finalReviewReportPath:path.join(f.attemptDir,"review-report.json"),outputs:[{label:"user",path:"docs/AUTOCODEX_TEST.md",type:"file",contentAvailable:true}]}); const s=await buildUiSystemState(f.runDir); expect(s.outputs[0].path).toBe("docs/AUTOCODEX_TEST.md"); expect(s.outputs.some(o=>o.path==="AUTOCODEX_SESSION_REPORT.md")).toBe(true); });

test("output falls back to session report when no user file exists", async()=>{ const f=await fixture(); await writeBase(f); await writeFinalResult(f.runDir,{schemaVersion:1,runId:"run-1",status:"ACCEPTED",terminalMessage:"TASK COMPLETE",error:null,finalReviewVerdict:"ACCEPT",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:[],finalValidationStatus:"PASS",finalReviewReportPath:path.join(f.attemptDir,"review-report.json"),outputs:[]}); const s=await buildUiSystemState(f.runDir); expect(s.outputs[0].path).toBe("AUTOCODEX_SESSION_REPORT.md"); });

test("safe output access supports run artifacts, rejects traversal, and preserves download filename", async()=>{ const f=await fixture(); await writeBase(f); await writeFinalResult(f.runDir,{schemaVersion:1,runId:"run-1",status:"ACCEPTED",terminalMessage:"TASK COMPLETE",error:null,finalReviewVerdict:"ACCEPT",totalCodingAttempts:1,reworkAttempts:0,finalWorkspacePath:f.ws,finalChangedFiles:[],finalValidationStatus:"PASS",finalReviewReportPath:path.join(f.attemptDir,"review-report.json"),outputs:[],runArtifacts:[{label:"binary",path:"binary.bin",kind:"log",readable:false}]}); await writeFile(path.join(f.runDir,"binary.bin"),Buffer.from([1,2,3])); await expect(readRunOutput("run-1","../secret",{cwd:f.root,runsDir:path.join(f.root,"runs")})).rejects.toThrow("Path traversal rejected"); await expect(readRunOutput("run-1","binary.bin",{cwd:f.root,runsDir:path.join(f.root,"runs")})).rejects.toThrow("not readable"); await expect(resolveRunDownload("run-1","AUTOCODEX_SESSION_REPORT.md",{cwd:f.root,runsDir:path.join(f.root,"runs")})).resolves.toMatchObject({filename:"AUTOCODEX_SESSION_REPORT.md"}); });

test("frontend output and details MVP affordances are compact", async()=>{ const app = await readFile(new URL("../src/ui/app.js", import.meta.url), "utf8"); const html = await readFile(new URL("../src/ui/index.html", import.meta.url), "utf8"); const css = await readFile(new URL("../src/ui/app.css", import.meta.url), "utf8"); expect(html).not.toContain('<pre id="viewer"></pre>'); expect(html).toContain('id="download"'); expect(app).toContain("meta&&(meta.readable===false||meta.contentAvailable===false)"); expect(app).toContain("/download?path="); expect(css).toContain("#viewer{display:none}"); expect(css).toContain("max-height:180px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere"); });
