import { expect, test } from "vitest";
import { readFile } from "node:fs/promises";
import { createBranchLoader, findRepository } from "../src/ui/repositorySelection.js";

test("UI script and markup render repository-first controls", async()=>{ const app=await readFile(new URL("../src/ui/app.js", import.meta.url),"utf8"); expect(app).toContain("function renderRepositoryOptions(repositories)"); expect(app).toContain("r.source==='github'?(r.fullName||r.name):r.name"); expect(app).toContain("/api/github/repositories"); expect(app).toContain("/api/github/clone-branch"); expect(app).not.toContain("function repoLabel(r){return r.name;}"); expect(app).not.toContain("gpt-handoff"); const html=await readFile(new URL("../src/ui/index.html", import.meta.url),"utf8"); expect(html).toContain("No output selected"); expect(html).toContain("Repository"); expect(html).toContain("Repository path"); expect(html).toContain("<input id=\"repositoryPath\" readonly>"); expect(html).toContain("id=\"refresh\""); expect(html).toContain("id=\"copy\""); expect(html).toContain("type=\"module\" src=\"/app.js\""); expect(html).not.toContain("copyText"); expect(html).not.toContain("projectStatus"); expect(html).not.toContain("Project"); expect(html).not.toContain("Profile"); expect(html).not.toContain("Sandbox"); });

test("repository labels use short local names and full GitHub names without filesystem paths", async()=>{ const app=await readFile(new URL("../src/ui/app.js", import.meta.url),"utf8"); expect(app).toContain("r.source==='github'?(r.fullName||r.name):r.name"); expect(app).toContain("value=\"${esc(r.id)}\""); expect(app).not.toContain("repo.localPath||repo.path||repo.name"); });

test("post-clone repository matching is stable",()=>{ const repos=[{id:"catos",source:"local",name:"CatOS",localPath:"/repos/CatOS",fullName:"catsystemexe/CatOS"},{id:"notecat-local",source:"local",name:"NoteCat",localPath:"/repos/NoteCat",fullName:"catsystemexe/NoteCat"},{id:"github:other",source:"github",name:"other",fullName:"catsystemexe/other"}]; expect(findRepository(repos,{localPath:"/repos/notecat/"})?.id).toBe("notecat-local"); expect(findRepository(repos,{fullName:"CATSYSTEMEXE/NOTECAT"})?.id).toBe("notecat-local"); expect(findRepository(repos,{id:"github:other"})?.id).toBe("github:other"); expect(findRepository(repos,{id:"missing"})).toBeUndefined(); });

test("post-clone reload selects NoteCat instead of falling back to first CatOS",()=>{ const reloaded=[{id:"catos",source:"local",name:"CatOS",localPath:"/repos/CatOS",fullName:"catsystemexe/CatOS"},{id:"notecat-local",source:"local",name:"NoteCat",localPath:"/repos/NoteCat",fullName:"catsystemexe/NoteCat"}]; const cloneResponse={id:"github:catsystemexe/notecat",source:"local",name:"NoteCat",localPath:"/repos/notecat",fullName:"CatsystemExe/NoteCat"}; const matched=findRepository(reloaded,cloneResponse); expect(matched?.name).toBe("NoteCat"); expect(matched?.id).not.toBe("catos"); });

test("branch request guard keeps latest repository branches",async()=>{ const catos={id:"catos",localPath:"/repos/CatOS"}; const notecat={id:"notecat",localPath:"/repos/NoteCat"}; let selected=catos; let catosDone:(v:{branches:{name:string}[]})=>void=()=>{}; let notecatDone:(v:{branches:{name:string}[]})=>void=()=>{}; let applied:{base:string;target:string}|undefined; const loader=createBranchLoader({getSelectedRepository:()=>selected,fetchBranches:repoPath=>new Promise<{ branches: { name: string }[] }>(resolve=>{ if(repoPath.includes("CatOS")) catosDone=resolve; else notecatDone=resolve; }),applyBranches:branches=>{applied={base:branches[0]?.name||"",target:branches[0]?.name||""};},clearBranches:()=>{applied={base:"",target:""};},setError:()=>{}}); const old=loader.load(catos); selected=notecat; const current=loader.load(notecat); notecatDone({branches:[{name:"notecat-main"}]}); await current; catosDone({branches:[{name:"catos-main"}]}); await old; expect(applied).toEqual({base:"notecat-main",target:"notecat-main"}); });

test("frontend clone flow sends selected remote branch and keeps clone selected after refresh", async()=>{ const app=await readFile(new URL("../src/ui/app.js", import.meta.url),"utf8"); expect(app).toContain("repositoryRequestVersion"); expect(app).toContain("/api/github/branches?repositoryId="); expect(app).toContain("body:JSON.stringify({repositoryId:repo.id,branch:$('base').value})"); expect(app).toContain("await loadRepositories(res.repository)"); expect(app).toContain("Cloned repository was not found after refresh."); expect(app).toContain("$('run').disabled=!local||!$('task').value.trim()"); });
