let runId='',started=0,selected='FINAL_REPORT.md',latestRows=[],latestSystem=null,latestOutputs=[],branches=[],cloneBusy=false,repositoryRequestVersion=0,checkout=null,phase='idle',statusMessage='No run started.',pollSequence=0,pollFailures=0,selectedStepPath='',manualStepSelection=false,loadingStepPath='';
const terminalPhases=new Set(['completed','failed','stopped']);
const activeStopPhases=new Set(['starting','running','stopping']);
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const mmss=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
const msfmt=ms=>ms==null?'':mmss(ms/1000);
const safeMessage=e=>String(e?.message||e||'unknown error').slice(0,240);
async function api(url,opt){const r=await fetch(url,opt); const j=await r.json().catch(()=>({})); if(!r.ok||j.error){const e=new Error(j.error?.message||r.statusText); e.code=j.error?.code; throw e;} return j;}
function setPhase(next,message){if(terminalPhases.has(phase)&&next==='running')return; phase=next; if(message)statusMessage=message; $('status').textContent=phase; updateRepositoryState(); renderRunMessage();}
function selectedRepository(){return (window.repositories||[]).find(r=>r.id===$('repository').value);}
function selectedRepositoryLabel(){const repo=selectedRepository(); return repo ? (repo.fullName||repo.name||repo.id) : 'No repository selected';}
function renderRepositoryOptions(repositories){const gh=repositories.filter(r=>r.source==='github'); $('repository').innerHTML=gh.map(r=>`<option value="${esc(r.id)}">${esc(r.fullName||r.name)}</option>`).join('')||'<option value="">No repositories found</option>'; $('selectedRepositoryName').textContent=selectedRepositoryLabel();}
function branchOptions(value){return branches.map(b=>`<option value="${esc(b.name)}" ${b.name===value?'selected':''}>${esc(b.name)}</option>`).join('');}
function defaultBranch(repo){return branches.find(b=>b.default)?.name || repo?.defaultBranch || branches.find(b=>b.name==='main')?.name || branches.find(b=>b.name==='master')?.name || branches[0]?.name || '';}
function clearCheckout(){checkout=null; $('repositoryPath').textContent='not cloned'; $('baseBranch').textContent='-';}
function updateRepositoryState(){const repo=selectedRepository(); const hasBranch=!!$('branch').value; const ready=!!checkout&&!!checkout.localPath&&!!checkout.branch&&!!$('task').value.trim()&&!activeStopPhases.has(phase); $('selectedRepositoryName').textContent=selectedRepositoryLabel(); $('repositoryPath').textContent=cloneBusy?'cloning...':(checkout?.localPath||'not cloned'); $('baseBranch').textContent=checkout?.branch||'-'; $('clone').disabled=!repo||!hasBranch||cloneBusy; $('clone').textContent=cloneBusy?'CLONING…':'CLONE BRANCH'; $('run').disabled=!ready; $('stop').disabled=!activeStopPhases.has(phase);}
async function loadBranches(repo){const request=++repositoryRequestVersion; branches=[]; $('branch').innerHTML=''; clearCheckout(); if(!repo){$('branchStatus').textContent='No branches available';updateRepositoryState();return;} $('branchStatus').textContent='Loading branches...'; updateRepositoryState(); try{const res=await api(`/api/github/branches?repositoryId=${encodeURIComponent(repo.id)}`); if(request!==repositoryRequestVersion)return; branches=res.branches||[]; if(!branches.length){$('branch').innerHTML='<option value="">No branches available</option>'; $('branchStatus').textContent='No branches available'; updateRepositoryState(); return;} const b=defaultBranch(repo); $('branch').innerHTML=branchOptions(b); $('branch').value=b; $('branchStatus').textContent=''; updateRepositoryState();}catch(e){if(request!==repositoryRequestVersion)return; $('branchStatus').textContent=safeMessage(e); updateRepositoryState();}}
async function loadRepositories(selectId){setPhase('idle','Loading repositories...'); const version=++repositoryRequestVersion; const previous=selectId||$('repository').value; const res=await api('/api/github/repositories'); if(version!==repositoryRequestVersion)return; window.repositories=res.repositories.filter(r=>r.source==='github'); renderRepositoryOptions(window.repositories); if(res.github&&!res.github.available)$('runReason').textContent=res.github.error||'GitHub repositories unavailable.'; if(!window.repositories.length){clearCheckout(); $('branchStatus').textContent='No branches available'; setPhase('idle','No run started.'); updateRepositoryState();return;} $('repository').value=window.repositories.some(r=>r.id===previous)?previous:window.repositories[0].id; $('selectedRepositoryName').textContent=selectedRepositoryLabel(); await loadBranches(selectedRepository()); setPhase('idle','No run started.');}
async function cloneSelected(){const repo=selectedRepository(); if(!repo)return; try{cloneBusy=true; $('runReason').textContent='cloning...'; updateRepositoryState(); const res=await api('/api/github/clone-branch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repositoryId:repo.id,branch:$('branch').value})}); checkout=res.checkout; cloneBusy=false; $('runReason').textContent=''; setPhase('idle','No run started.'); updateRepositoryState();}catch(e){cloneBusy=false;checkout=null;updateRepositoryState();$('runReason').textContent=safeMessage(e);}}
async function start(){try{if(!checkout)throw new Error('RUN requires a cloned branch checkout.'); runId=''; selected='FINAL_REPORT.md'; selectedStepPath=''; manualStepSelection=false; loadingStepPath=''; latestRows=[]; started=Date.now(); $('runNo').textContent='RUN #-'; $('viewerTitle').textContent='FINAL_REPORT.md'; $('stepViewer').textContent='Select a step to view its output.'; $('copyStatus').textContent=''; $('copy').disabled=true; $('download').disabled=true; setPhase('starting','Creating run snapshot…'); const payload={repositoryPath:checkout.localPath,baseBranch:checkout.branch,prTargetBranch:checkout.branch,task:$('task').value}; const res=await api('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); if(!res.runId){runId=''; $('runNo').textContent='RUN #-'; setPhase('failed','Run was not created.'); return;} runId=res.runId; started=Date.now(); pollFailures=0; $('runNo').textContent=`RUN #${runId}`; setPhase('running','Waiting for first timeline event…'); await refreshRun();}catch(e){runId=''; setPhase('failed',safeMessage(e)); $('runReason').textContent=safeMessage(e);}}
function rowOutputPath(r){return r.output?.path||r.path||'';}
function rowStep(r){return r.name||r.label||r.type||'Unnamed step';}
function rowTime(r){return msfmt(r.durationMs)||r.finishedAt||r.startedAt||'';}
function renderRunMessage(){$('status').textContent=phase;}
function copyButtonClass(base,available){return `${base} ${available?'copy-available':'copy-unavailable'}`;}
function stepResultFile(r){return r.resultFile||{label:r.artifactPath,path:r.artifactPath,exists:false,readable:false};}
function autoSelectCandidate(){if(!latestRows.length)return null; if(terminalPhases.has(phase)){return latestRows.find(r=>['failed','rework'].includes(String(r.status||'').toLowerCase()))||[...latestRows].reverse().find(r=>String(r.status||'').toLowerCase()==='completed')||latestRows.at(-1);} return latestRows.find(r=>String(r.status||'').toLowerCase()==='running')||null;}
function maybeAutoSelectStep(){if(manualStepSelection)return; if(selectedStepPath&&!terminalPhases.has(phase))return; const r=autoSelectCandidate(); if(!r)return; const rf=stepResultFile(r); if(rf?.path) selectStep(rf.path,false);}
async function loadStepOutput(path, preserveScroll=false){if(!path||!runId)return; const viewer=$('stepViewer'); const top=viewer.scrollTop; loadingStepPath=path; viewer.textContent='Loading step output…'; try{const res=await api(`/api/runs/${runId}/output?path=${encodeURIComponent(path)}`); if(loadingStepPath!==path)return; viewer.textContent=res.content||''; if(preserveScroll)viewer.scrollTop=top;}catch(e){if(loadingStepPath!==path)return; const row=latestRows.find(r=>stepResultFile(r)?.path===path); const rf=row?stepResultFile(row):null; viewer.textContent=rf&&(!rf.exists||!rf.readable)?'Step output unavailable.':'Could not load step output.'; if(preserveScroll)viewer.scrollTop=top;}}
function selectStep(path,manual=true){if(!path)return; selectedStepPath=path; if(manual)manualStepSelection=true; document.querySelectorAll('.timeline-row').forEach(row=>row.classList.toggle('selected',row.dataset.stepPath===path)); loadStepOutput(path,false);}
function renderRows(){if(!latestRows.length){$('timeline').innerHTML=''; renderRunMessage(); return;} const rows=latestRows.map((r,i)=>{const rf=stepResultFile(r); const available=!!rf?.exists&&!!rf?.readable&&!!rf?.path; const disabled=available?'':' disabled'; const title=available?'Copy result file':'Result file unavailable'; const selectedClass=rf?.path&&rf.path===selectedStepPath?' selected':''; return `<div class="timeline-row${selectedClass}" data-step-path="${esc(rf?.path||'')}"><div class="timeline-index">${r.index||i+1}</div><div class="timeline-step">${esc(rowStep(r)).toUpperCase()}</div><div class="timeline-status">${esc(r.status||'waiting')}</div><div class="timeline-time">${esc(rowTime(r))}</div><button class="${copyButtonClass('step-copy',available)}" type="button" title="${title}" data-step-path="${esc(rf?.path||'')}"${disabled}>COPY</button></div>`;}).join(''); $('timeline').innerHTML=rows; maybeAutoSelectStep(); renderRunMessage();}
function renderOutputs(){const report=latestSystem?.finalReport||{label:'FINAL_REPORT.md',path:'FINAL_REPORT.md',readable:false,downloadable:false}; latestOutputs=[report]; selected=report.path; $('viewerTitle').textContent=report.label||'FINAL_REPORT.md'; const copyAvailable=!!report.readable; $('copy').disabled=!copyAvailable; $('copy').title=copyAvailable?'Copy final report':'Result file unavailable'; $('copy').className=copyAvailable?'copy-available':'copy-unavailable'; $('download').disabled=!report.downloadable; $('download').title=report.downloadable?'Download final report':'Result file unavailable';}
async function refreshRun(){if(!runId||terminalPhases.has(phase))return; const seq=++pollSequence; try{const s=await api(`/api/runs/${runId}`); if(seq!==pollSequence)return; const next=s.status||'running'; if(next==='completed'||next==='failed'||next==='stopped')setPhase(next,next); else if(phase!=='stopping')setPhase('running',latestRows.length?'Running.':'Waiting for first timeline event…'); $('elapsed').textContent=mmss((Date.now()-started)/1000); if(s.system){ latestSystem=s.system; renderOutputs(); } const t=await api(`/api/runs/${runId}/timeline`); if(seq!==pollSequence)return; latestRows=t.rows||[]; pollFailures=0; if(!latestRows.length&&phase==='running')statusMessage='Waiting for first timeline event…'; renderRows(); renderOutputs(); if(selectedStepPath&&latestRows.some(r=>stepResultFile(r)?.path===selectedStepPath&&String(r.status||'').toLowerCase()==='running')) loadStepOutput(selectedStepPath,true); updateRepositoryState();}catch(e){if(seq!==pollSequence)return; pollFailures+=1; statusMessage=`Timeline unavailable: ${safeMessage(e)}`; updateRepositoryState();}}
async function stop(){if(!runId)return; try{setPhase('stopping','Stopping run…'); const res=await api(`/api/runs/${runId}/stop`,{method:'POST'}); setPhase(res.status==='stopped'?'stopped':'stopping',res.status==='stopped'?'stopped':'Stopping run…');}catch(e){setPhase('failed',safeMessage(e));}}
function flashCopyButton(b,cls,text,restoreAvailable){ const old=b.textContent; b.classList.remove('copy-success','copy-error'); b.classList.add(cls); b.textContent=text; setTimeout(()=>{b.classList.remove(cls); b.textContent=old||'COPY'; b.classList.toggle('copy-available',!!restoreAvailable); b.classList.toggle('copy-unavailable',!restoreAvailable);},1500); }
async function copyLoadedContent(text){try{await copyText(text); return true;}catch(e){return false;}}
document.body.addEventListener('click',async e=>{const b=e.target.closest?.('button[data-step-path]'); if(!b)return; e.stopPropagation(); const available=!b.disabled&&!!b.dataset.stepPath; if(!available){$('copyStatus').textContent='Result file unavailable.'; return;} let res; try{res=await api(`/api/runs/${runId}/output?path=${encodeURIComponent(b.dataset.stepPath)}`);}catch(e){ $('copyStatus').textContent='Could not load result file.'; flashCopyButton(b,'copy-error','ERROR',true); return;} if(await copyLoadedContent(res.content||'')){ $('copyStatus').textContent='Copied.'; flashCopyButton(b,'copy-success','COPIED',true); } else { $('copyStatus').textContent='Clipboard unavailable.'; flashCopyButton(b,'copy-error','ERROR',true); }});
document.body.addEventListener('click',e=>{const row=e.target.closest?.('.timeline-row'); if(!row||e.target.closest?.('button'))return; selectStep(row.dataset.stepPath,true);});
$('repository').onchange=async()=>{clearCheckout(); $('selectedRepositoryName').textContent=selectedRepositoryLabel(); await loadBranches(selectedRepository());};
async function copyText(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text); return;}catch(clipboardError){
    // Fall through to legacy textarea copy.
  } } const area=document.createElement('textarea'); area.value=text; area.setAttribute('readonly',''); area.style.position='fixed'; area.style.left='-9999px'; document.body.appendChild(area); area.select(); const ok=document.execCommand('copy'); area.remove(); if(!ok)throw new Error('Clipboard unavailable.');}
$('clone').onclick=cloneSelected; $('branch').onchange=()=>{clearCheckout(); updateRepositoryState();}; $('task').oninput=updateRepositoryState; $('run').onclick=start; $('stop').onclick=stop; $('copy').onclick=async()=>{const b=$('copy'); const report=latestSystem?.finalReport; if(!report?.readable){$('copyStatus').textContent='Result file unavailable.'; return;} let res; try{res=await api(`/api/runs/${runId}/output?path=${encodeURIComponent(report.path)}`);}catch(e){ $('copyStatus').textContent='Could not load result file.'; flashCopyButton(b,'copy-error','ERROR',true); return;} if(await copyLoadedContent(res.content||'')){ $('copyStatus').textContent='Copied.'; flashCopyButton(b,'copy-success','COPIED',true); } else { $('copyStatus').textContent='Clipboard unavailable.'; flashCopyButton(b,'copy-error','ERROR',true); }}; $('download').onclick=()=>{const report=latestSystem?.finalReport; if(report?.downloadable) window.location.href=`/api/runs/${runId}/download?path=${encodeURIComponent(report.path)}`; else $('copyStatus').textContent='Download failed';};
setInterval(refreshRun,1500); loadRepositories().catch(e=>{$('runReason').textContent=safeMessage(e); setPhase('failed',safeMessage(e));});
export {renderRepositoryOptions,updateRepositoryState,cloneSelected,start,renderRows,refreshRun,setPhase,selectStep,loadStepOutput,maybeAutoSelectStep};
