let runId='',started=0,selected='',latestRows=[],spinnerIndex=0,branches=[],cloneBusy=false,repositoryRequestVersion=0,checkout=null; const spinnerFrames=['|','/','-','\\']; const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); const mmss=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
async function api(url,opt){const r=await fetch(url,opt); const j=await r.json().catch(()=>({})); if(!r.ok||j.error){const e=new Error(j.error?.message||r.statusText); e.code=j.error?.code; throw e;} return j;}
function selectedRepository(){return (window.repositories||[]).find(r=>r.id===$('repository').value);}
function renderRepositoryOptions(repositories){const gh=repositories.filter(r=>r.source==='github'); $('repository').innerHTML=gh.map(r=>`<option value="${esc(r.id)}">${esc(r.fullName||r.name)}</option>`).join('')||'<option value="">No repositories found</option>';}
function branchOptions(value){return branches.map(b=>`<option value="${esc(b.name)}" ${b.name===value?'selected':''}>${esc(b.name)}</option>`).join('');}
function defaultBranch(repo){return branches.find(b=>b.default)?.name || repo?.defaultBranch || branches.find(b=>b.name==='main')?.name || branches.find(b=>b.name==='master')?.name || branches[0]?.name || '';}
function updateRepositoryState(){const repo=selectedRepository(); const ready=!!checkout&&!!$('branch').value&&!!$('task').value.trim(); $('repositoryPath').value=cloneBusy?'cloning...':(checkout?.localPath||''); $('clone').hidden=!repo; $('clone').disabled=!repo||!$('branch').value||cloneBusy; $('run').disabled=!ready;}
async function loadBranches(repo){branches=[]; $('branch').innerHTML=''; checkout=null; if(!repo){updateRepositoryState();return;} const res=await api(`/api/github/branches?repositoryId=${encodeURIComponent(repo.id)}`); branches=res.branches; const b=defaultBranch(repo); $('branch').innerHTML=branchOptions(b); $('branch').value=b; updateRepositoryState();}
async function loadRepositories(selectId){const version=++repositoryRequestVersion; const previous=selectId||$('repository').value; const res=await api('/api/github/repositories'); if(version!==repositoryRequestVersion)return; window.repositories=res.repositories.filter(r=>r.source==='github'); renderRepositoryOptions(window.repositories); if(res.github&&!res.github.available)$('runReason').textContent=res.github.error||'GitHub repositories unavailable.'; if(!window.repositories.length){updateRepositoryState();return;} $('repository').value=window.repositories.some(r=>r.id===previous)?previous:window.repositories[0].id; await loadBranches(selectedRepository());}
async function cloneSelected(){const repo=selectedRepository(); if(!repo)return; try{cloneBusy=true; $('runReason').textContent='cloning...'; updateRepositoryState(); const res=await api('/api/github/clone-branch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repositoryId:repo.id,branch:$('branch').value})}); checkout=res.checkout; cloneBusy=false; $('runReason').textContent=''; updateRepositoryState();}catch(e){cloneBusy=false;checkout=null;updateRepositoryState();$('runReason').textContent=e.message;}}
async function start(){try{if(!checkout)throw new Error('RUN requires a cloned branch checkout.'); const payload={repositoryPath:checkout.localPath,baseBranch:checkout.branch,prTargetBranch:checkout.branch,task:$('task').value}; const res=await api('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); runId=res.runId; started=Date.now(); $('runNo').textContent=`RUN #${runId||'-'}`; await refreshRun();}catch(e){$('runReason').textContent=e.message;}}
function renderRows(){const rows=latestRows.map((r,i)=>`<div data-i="${i}" class="row ${selected===r.path?'sel':''}">${r.status==='running'?spinnerFrames[spinnerIndex]:' '} ${esc(r.path)} ${esc(r.summary||'')}</div>`).join(''); $('timeline').innerHTML=rows||'<div>No output selected</div>';}
async function refreshRun(){if(!runId)return; try{const s=await api(`/api/runs/${runId}`); $('status').textContent=s.status||'running'; $('elapsed').textContent=mmss((Date.now()-started)/1000); const t=await api(`/api/runs/${runId}/timeline`); latestRows=t.rows||[]; renderRows();}catch{}}
async function stop(){if(runId)await api(`/api/runs/${runId}/stop`,{method:'POST'});} function view(){}
document.body.addEventListener('click',e=>{if(e.target.dataset.view)view(e.target.dataset.view);}); $('repository').onchange=async()=>{checkout=null; await loadBranches(selectedRepository());}; $('refresh').onclick=()=>loadRepositories().catch(e=>{$('runReason').textContent=e.message;}); $('clone').onclick=cloneSelected; $('branch').onchange=()=>{checkout=null; updateRepositoryState();}; $('task').oninput=updateRepositoryState; $('run').onclick=start; $('stop').onclick=stop; $('copy').onclick=()=>{if(selected)navigator.clipboard?.writeText($('viewer').textContent);}; setInterval(refreshRun,1500); setInterval(()=>{spinnerIndex=(spinnerIndex+1)%spinnerFrames.length; renderRows();},200); loadRepositories().catch(e=>{$('runReason').textContent=e.message;});
export {renderRepositoryOptions,updateRepositoryState,cloneSelected,start};
