let runId='',started=0,latestRows=[],latestSystem=null,branches=[],cloneBusy=false,repositoryRequestVersion=0,checkout=null,phase='idle',statusMessage='No run started.',pollSequence=0,pollFailures=0,selectedStepPath='',manualStepSelection=false,loadingStepPath='',viewContent='';
const terminalPhases=new Set(['completed','failed','stopped']);
const activeStopPhases=new Set(['starting','running','stopping']);
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const mmss=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.floor(Math.max(0,s)%60)).padStart(2,'0')}`;
const msfmt=ms=>ms==null?'':mmss(ms/1000);
const safeMessage=e=>String(e?.message||e||'unknown error').slice(0,240);
async function api(url,opt){const r=await fetch(url,opt); const j=await r.json().catch(()=>({})); if(!r.ok||j.error){const e=new Error(j.error?.message||r.statusText); e.code=j.error?.code; throw e;} return j;}
function setPhase(next,message){if(terminalPhases.has(phase)&&next==='running')return; phase=next; if(message)statusMessage=message; $('status').textContent=phase; updateRepositoryState(); renderRunMessage();}
function selectedRepository(){return (window.repositories||[]).find(r=>r.id===$('repository').value);}
function selectedRepositoryLabel(){const repo=selectedRepository(); return repo ? (repo.fullName||repo.name||repo.id) : 'No repository selected';}
function renderRepositoryOptions(repositories){const gh=repositories.filter(r=>r.source==='github'); $('repository').innerHTML=gh.map(r=>`<option value="${esc(r.id)}">${esc(r.fullName||r.name)}</option>`).join('')||'<option value="">No repositories found</option>'; $('selectedRepositoryName').textContent=selectedRepositoryLabel();}
function branchOptions(value){return branches.map(b=>`<option value="${esc(b.name)}" ${b.name===value?'selected':''}>${esc(b.name)}</option>`).join('');}
function defaultBranch(repo){return branches.find(b=>b.default)?.name || repo?.defaultBranch || branches.find(b=>b.name==='main')?.name || branches.find(b=>b.name==='master')?.name || branches[0]?.name || '';}
function clearCheckout(){checkout=null; $('repositoryPath').textContent='not cloned'; $('baseBranch').textContent='-';}
function updateRepositoryState(){const repo=selectedRepository(); const hasBranch=!!$('branch').value; const ready=!!checkout&&!!checkout.localPath&&!!checkout.branch&&!!$('task').value.trim()&&!activeStopPhases.has(phase); $('selectedRepositoryName').textContent=selectedRepositoryLabel(); $('repositoryPath').textContent=cloneBusy?'cloning...':(checkout?.localPath||'not cloned'); $('baseBranch').textContent=checkout?.branch||'-'; $('clone').disabled=!repo||!hasBranch||cloneBusy; $('clone').textContent=cloneBusy?'CLONING…':'CLONE BRANCH'; $('run').disabled=!ready; $('stop').disabled=!activeStopPhases.has(phase);}
async function loadBranches(repo){const request=++repositoryRequestVersion; branches=[]; $('branch').innerHTML=''; clearCheckout(); if(!repo){$('branchStatus').textContent='No branches available';updateRepositoryState();return;} $('branchStatus').textContent='Loading branches...'; updateRepositoryState(); try{const res=await api(`/api/github/branches?repositoryId=${encodeURIComponent(repo.id)}`); if(request!==repositoryRequestVersion)return; branches=res.branches||[]; if(!branches.length){$('branch').innerHTML='<option value="">No branches available</option>'; $('branchStatus').textContent='No branches available'; updateRepositoryState(); return;} const b=defaultBranch(repo); $('branch').innerHTML=branchOptions(b); $('branch').value=b; $('branchStatus').textContent=''; updateRepositoryState();}catch(e){if(request!==repositoryRequestVersion)return; $('branchStatus').textContent=safeMessage(e); updateRepositoryState();}}
async function loadRepositories(selectId){setPhase('idle','Loading repositories...'); const version=++repositoryRequestVersion; const previous=selectId||$('repository').value; const res=await api('/api/github/repositories'); if(version!==repositoryRequestVersion)return; window.repositories=res.repositories.filter(r=>r.source==='github'); renderRepositoryOptions(window.repositories); if(res.github&&!res.github.available)$('runReason').textContent=res.github.error||'GitHub repositories unavailable.'; if(!window.repositories.length){clearCheckout(); $('branchStatus').textContent='No branches available'; setPhase('idle','No run started.'); updateRepositoryState();return;} $('repository').value=window.repositories.some(r=>r.id===previous)?previous:window.repositories[0].id; $('selectedRepositoryName').textContent=selectedRepositoryLabel(); await loadBranches(selectedRepository()); setPhase('idle','No run started.');}
async function cloneSelected(){const repo=selectedRepository(); if(!repo)return; try{cloneBusy=true; $('runReason').textContent='cloning...'; updateRepositoryState(); const res=await api('/api/github/clone-branch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repositoryId:repo.id,branch:$('branch').value})}); checkout=res.checkout; cloneBusy=false; $('runReason').textContent=''; setPhase('idle','No run started.'); updateRepositoryState();}catch(e){cloneBusy=false;checkout=null;updateRepositoryState();$('runReason').textContent=safeMessage(e);}}
async function start(){try{if(!checkout)throw new Error('RUN requires a cloned branch checkout.'); runId=''; selectedStepPath=''; manualStepSelection=false; loadingStepPath=''; latestRows=[]; viewContent=''; started=Date.now(); $('runNo').textContent='RUN #-'; $('viewerTitle').textContent='VIEW'; $('stepViewer').textContent='Select a report to view.'; $('copyStatus').textContent=''; $('copy').disabled=true; setPhase('starting','Creating run snapshot…'); const payload={repositoryPath:checkout.localPath,baseBranch:checkout.branch,prTargetBranch:checkout.branch,task:$('task').value}; const res=await api('/api/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); if(!res.runId){runId=''; $('runNo').textContent='RUN #-'; setPhase('failed','Run was not created.'); return;} runId=res.runId; started=Date.now(); pollFailures=0; $('runNo').textContent=`RUN #${runId}`; setPhase('running','Waiting for first timeline event…'); await refreshRun();}catch(e){runId=''; setPhase('failed',safeMessage(e)); $('runReason').textContent=safeMessage(e);}}
function rowOutputPath(r){return r.output?.path||r.path||'';}
function rowStep(r){return r.label||r.name||r.type||'Unnamed step';}
function actorIcon(r){const actor=String(r.actor||'').toLowerCase(); if(actor==='codex')return '<span class="timeline-icon codex-icon" aria-label="Codex" title="Codex">C</span>'; if(actor==='gpt')return '<span class="timeline-icon gpt-icon" aria-label="GPT" title="GPT">G</span>'; return '<span class="timeline-icon script-icon" aria-label="Script" title="Script">⌘</span>';}
function rowTime(r){return msfmt(r.durationMs)||r.finishedAt||r.startedAt||'';}
function renderRunMessage(){$('status').textContent=phase;}
function stepResultFile(r){return r.report||r.resultFile||{label:r.artifactPath,path:r.artifactPath,exists:false,readable:false};}
function reportHeading(r){return r?.phase==='final'||r?.name==='FINAL'?'VIEW — FINAL REPORT':`VIEW — ${String(r?.label||r?.name||'')} REPORT`;}
function autoSelectCandidate(){if(!latestRows.length)return null; if(terminalPhases.has(phase)){const review=latestRows.find(r=>r.name==='REVIEW'&&['failed','rework','human_required'].includes(String(r.status||'').toLowerCase())); return review||latestRows.find(r=>r.name==='FINAL')||latestRows.at(-1);} return latestRows.find(r=>String(r.status||'').toLowerCase()==='running')||null;}
function maybeAutoSelectStep(){if(manualStepSelection)return; if(selectedStepPath&&!terminalPhases.has(phase))return; const r=autoSelectCandidate(); if(!r)return; const rf=stepResultFile(r); if(rf?.path) selectStep(rf.path,false);}
async function loadStepOutput(path, preserveScroll=false){if(!path||!runId)return; const viewer=$('stepViewer'); const top=viewer.scrollTop; loadingStepPath=path; viewContent=''; viewer.textContent='Loading report…'; $('copy').disabled=true; try{const res=await api(`/api/runs/${runId}/output?path=${encodeURIComponent(path)}`); if(loadingStepPath!==path)return; viewContent=res.content||''; viewer.textContent=viewContent; $('copy').disabled=false; if(preserveScroll)viewer.scrollTop=top;}catch(e){if(loadingStepPath!==path)return; const row=latestRows.find(r=>stepResultFile(r)?.path===path); const rf=row?stepResultFile(row):null; viewContent=''; viewer.textContent=rf&&(!rf.exists||!rf.readable)?'Report unavailable.':'Could not load report.'; $('copy').disabled=true; if(preserveScroll)viewer.scrollTop=top;}}
function selectStep(path,manual=true){if(!path)return; selectedStepPath=path; if(manual)manualStepSelection=true; const rowData=latestRows.find(r=>stepResultFile(r)?.path===path); $('viewerTitle').textContent=reportHeading(rowData); document.querySelectorAll('.timeline-row').forEach(row=>row.classList.toggle('selected',row.dataset.stepPath===path)); loadStepOutput(path,false);}
function renderRows(){if(!latestRows.length){$('timeline').innerHTML=''; renderRunMessage(); return;} const rows=latestRows.map((r,i)=>{const rf=stepResultFile(r); const available=!!rf?.exists&&!!rf?.readable&&!!rf?.path; const disabled=available?'':' disabled'; const title=available?'Open report':'Report unavailable'; const selectedClass=rf?.path&&rf.path===selectedStepPath?' selected':''; const action=r.phase==='final'||r.name==='FINAL'?'FINAL REPORT':'REPORT'; return `<div class="timeline-row${selectedClass}" data-step-path="${esc(rf?.path||'')}"><div class="timeline-index">${r.index||i+1}</div><div class="timeline-step">${actorIcon(r)}<span>${esc(rowStep(r))}</span></div><div class="timeline-status">${esc(r.status||'waiting')}</div><div class="timeline-time">${esc(rowTime(r))}</div><button class="report-action ${available?'copy-available':'copy-unavailable'}" type="button" title="${title}" data-step-path="${esc(rf?.path||'')}"${disabled}>${action}</button></div>`;}).join(''); $('timeline').innerHTML=rows; maybeAutoSelectStep(); renderRunMessage();}
function renderOutputs(){const selectedRow=latestRows.find(r=>stepResultFile(r)?.path===selectedStepPath); if(selectedRow)$('viewerTitle').textContent=reportHeading(selectedRow);}
async function refreshRun(){if(!runId||terminalPhases.has(phase))return; const seq=++pollSequence; try{const s=await api(`/api/runs/${runId}`); if(seq!==pollSequence)return; const next=s.status||'running'; if(next==='completed'||next==='failed'||next==='stopped')setPhase(next,next); else if(phase!=='stopping')setPhase('running',latestRows.length?'Running.':'Waiting for first timeline event…'); $('elapsed').textContent=mmss((Date.now()-started)/1000); if(s.system){ latestSystem=s.system; renderOutputs(); } const t=await api(`/api/runs/${runId}/timeline`); if(seq!==pollSequence)return; latestRows=t.rows||[]; pollFailures=0; if(!latestRows.length&&phase==='running')statusMessage='Waiting for first timeline event…'; renderRows(); renderOutputs(); if(selectedStepPath&&latestRows.some(r=>stepResultFile(r)?.path===selectedStepPath&&String(r.status||'').toLowerCase()==='running')) loadStepOutput(selectedStepPath,true); updateRepositoryState();}catch(e){if(seq!==pollSequence)return; pollFailures+=1; statusMessage=`Timeline unavailable: ${safeMessage(e)}`; updateRepositoryState();}}
async function stop(){if(!runId)return; try{setPhase('stopping','Stopping run…'); const res=await api(`/api/runs/${runId}/stop`,{method:'POST'}); setPhase(res.status==='stopped'?'stopped':'stopping',res.status==='stopped'?'stopped':'Stopping run…');}catch(e){setPhase('failed',safeMessage(e));}}
function flashCopyButton(b,cls,text,restoreAvailable){ const old=b.textContent; b.classList.remove('copy-success','copy-error'); b.classList.add(cls); b.textContent=text; setTimeout(()=>{b.classList.remove(cls); b.textContent=old||'COPY'; b.classList.toggle('copy-available',!!restoreAvailable); b.classList.toggle('copy-unavailable',!restoreAvailable);},1500); }
async function copyLoadedContent(text){try{return await copyText(text);}catch(e){return false;}}
document.body.addEventListener('click',e=>{const b=e.target.closest?.('button[data-step-path]'); if(!b)return; e.stopPropagation(); if(b.disabled||!b.dataset.stepPath){$('copyStatus').textContent='Report unavailable.'; return;} selectStep(b.dataset.stepPath,true);});
document.body.addEventListener('click',e=>{const row=e.target.closest?.('.timeline-row'); if(!row||e.target.closest?.('button'))return; selectStep(row.dataset.stepPath,true);});
$('repository').onchange=async()=>{clearCheckout(); $('selectedRepositoryName').textContent=selectedRepositoryLabel(); await loadBranches(selectedRepository());};
function manualCopyOverlay(text){const overlay=document.createElement('div'); overlay.className='manual-copy-overlay'; overlay.innerHTML='<strong>Manual copy</strong><textarea readonly></textarea><button type="button">CLOSE</button>'; const area=overlay.querySelector('textarea'); area.value=text; overlay.querySelector('button').onclick=()=>overlay.remove(); document.body.appendChild(overlay); area.focus(); area.select();}
async function copyText(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text); return true;}catch(clipboardError){} } const area=document.createElement('textarea'); area.value=text; area.setAttribute('readonly',''); area.style.position='fixed'; area.style.left='-9999px'; document.body.appendChild(area); area.select(); let ok=false; try{ok=document.execCommand('copy');}catch(e){ok=false;} area.remove(); if(ok)return true; manualCopyOverlay(text); return false;}
$('clone').onclick=cloneSelected; $('branch').onchange=()=>{clearCheckout(); updateRepositoryState();}; $('task').oninput=updateRepositoryState; $('run').onclick=start; $('stop').onclick=stop; $('copy').onclick=async()=>{const b=$('copy'); if(!viewContent){$('copyStatus').textContent='Report unavailable.'; return;} if(await copyLoadedContent(viewContent)){ $('copyStatus').textContent='Copied.'; flashCopyButton(b,'copy-success','COPIED',true); } else { $('copyStatus').textContent='Manual copy opened.'; flashCopyButton(b,'copy-error','COPY',true); }};
setInterval(refreshRun,1500); loadRepositories().catch(e=>{$('runReason').textContent=safeMessage(e); setPhase('failed',safeMessage(e));});
export {renderRepositoryOptions,updateRepositoryState,cloneSelected,start,renderRows,refreshRun,setPhase,selectStep,loadStepOutput,maybeAutoSelectStep};
