import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildValidationCommands, type ValidationCommand } from "./validationRunner.js";
import { loadProjectConfig } from "./config/loadConfig.js";
import type { Attempt, Decision, Session, Step } from "./runs/sessionModel.js";
import { readJson } from "./runs/sessionModel.js";

export type ContinueReason = "initial-step" | "retry" | "revise" | "manual-follow-up" | "validation-failure" | "review-rework" | "runtime-failure";
export type ContinueAction = "run-step" | "inspect";
export type ContinueValidationCommand = Pick<ValidationCommand, "name" | "command" | "required">;
export type ContinueAttemptSummary = { order: number; status: string; changedFiles: string[]; validationStatus?: string; reviewVerdict?: string; blockingFindings: string[]; warnings: string[]; errorSummary?: string; artifactReferences: Record<string,string> };
export type ContinuePackage = {
  schemaVersion: 1; generatedAt: string;
  session: { sessionId: string; goal: string; branch?: string; workspacePath?: string };
  activeStep: { stepId: string; order: number; title: string; request: string; status: string };
  execution: { nextAttemptOrder: number; threadId?: string; runtimeMode?: string; reason: ContinueReason; omittedPreviousAttempts: number };
  previousAttempts: ContinueAttemptSummary[];
  currentFindings: { blocking: string[]; warnings: string[]; validationFailures: string[]; runtimeErrors: string[] };
  humanDecision?: { type: string; reason?: string; requestedChanges?: string[] };
  constraints: string[];
  expectedValidation: ContinueValidationCommand[];
  relevantFiles: string[];
  artifactReferences: Record<string,string>;
  missingArtifacts: string[];
  recommendedAction: ContinueAction;
};

const ATTEMPT_LIMIT = 5;
const SYSTEM_CONSTRAINTS = [
  "Work only inside the guarded workspace.", "Preserve existing session and audit artifacts.", "Do not push, create a remote PR, or merge.", "Do not expose secrets or environment values.", "Run the configured validation commands.", "Preserve previous failed attempts in the audit history.",
];
const exactSecretValues = ["TEST_SECRET_VALUE", "test-secret-value", "known-test-secret-value-123"].sort((a,b)=>b.length-a.length);
const tokenPatterns = [/sk-(?:proj-)?[A-Za-z0-9_-]{20,}/g, /gh[pousr]_[A-Za-z0-9_]{20,}/g, /xox[baprs]-[A-Za-z0-9-]{20,}/g];
function esc(s:string): string { return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
export function scrubContinue(value: string): string { return exactSecretValues.reduce((out, secret) => out.replace(new RegExp(esc(secret), "g"), "[REDACTED]"), tokenPatterns.reduce((out,re)=>out.replace(re,"[REDACTED]"), value)); }
function clean<T>(v:T): T { return JSON.parse(scrubContinue(JSON.stringify(v))) as T; }
function uniq(values: Array<string|undefined>): string[] { return [...new Set(values.filter((v): v is string => !!v && v.trim().length > 0).map(v=>scrubContinue(v.trim())))].sort((a,b)=>a.localeCompare(b)); }
function line(v: unknown): string { return v === undefined || v === "" ? "not recorded" : String(v); }
async function findStepDir(runDir:string, step: Pick<Step,"order"|"stepId">): Promise<string> { const root=path.join(runDir,"steps"); const dirs=(await readdir(root)).sort(); const d=dirs.find(x=>x.endsWith(`-${step.stepId}`)); if(!d) throw new Error(`Step not found: ${step.stepId}`); return path.join(root,d); }
async function readOptionalJson<T>(runDir:string, rel:string|undefined, missing:string[], invalid:string[]): Promise<T|undefined> { if(!rel) return undefined; try { return await readJson<T>(path.join(runDir, rel)); } catch { missing.push(rel); return undefined; } }
function findingText(f: unknown): string | undefined { if (typeof f === "string") return f; if (f && typeof f === "object") { const r=f as Record<string,unknown>; return [r.file, r.message, r.requiredChange, r.severity].filter(Boolean).join(" — "); } return undefined; }
function filesFromFinding(f: unknown): string[] { if (f && typeof f === "object") { const r=f as Record<string,unknown>; return [r.file, r.path].filter((x):x is string=>typeof x === "string"); } return []; }
function validationFailures(report: any): string[] { return uniq((report?.results ?? []).filter((r:any)=>r.status && r.status !== "PASS").map((r:any)=>`${r.name}: exit ${r.exitCode ?? "null"} — ${String(r.stderr || r.stdout || r.status).split(/\n/).find(Boolean) ?? r.status}`)); }
function reviewBlocking(review:any): string[] { return uniq([...(review?.blockingFindings ?? []), ...(review?.requiredChanges ?? [])].map(findingText)); }
function reviewWarnings(review:any): string[] { return uniq((review?.warnings ?? []).map(findingText)); }
async function loadAttempts(runDir:string, step:Step, missing:string[], invalid:string[]): Promise<Attempt[]> { const sd=await findStepDir(runDir, step); const dirs=(await readdir(path.join(sd,"attempts")).catch(()=>[])).sort(); const out:Attempt[]=[]; for (const id of step.attempts) { const d=dirs.find(x=>x.endsWith(`-${id}`)); if(!d){missing.push(path.relative(runDir,path.join(sd,"attempts",`*-${id}`,"attempt.json"))); continue;} try{out.push(await readJson<Attempt>(path.join(sd,"attempts",d,"attempt.json")));}catch{invalid.push(path.relative(runDir,path.join(sd,"attempts",d,"attempt.json")));} } return out.sort((a,b)=>a.order-b.order); }
async function loadDecision(runDir:string, step:Step, missing:string[]): Promise<Decision|undefined> { try { const sd=await findStepDir(runDir, step); return await readJson<Decision>(path.join(sd,"decision.json")); } catch { return undefined; } }
function determineReason(step:Step, attempts:Attempt[], decision?:Decision, validation?:any, review?:any): ContinueReason { const last=attempts.at(-1); if(!last) return "initial-step"; if(last.status === "timed_out" || last.status === "failed" || /timeout|error/i.test(last.resultStatus ?? "")) return "runtime-failure"; if(decision?.type === "retry") return "retry"; if(decision?.type === "revise") return "revise"; if(String(review?.verdict).toUpperCase() === "REWORK") return "review-rework"; if(validation?.status === "FAIL" || validation?.status === "BLOCKED") return "validation-failure"; return step.order > 1 ? "manual-follow-up" : "retry"; }
export async function buildContinuePackage(runDir:string, now=new Date(), options:{cwd?:string}={}): Promise<ContinuePackage> {
  const missing:string[]=[]; const invalid:string[]=[]; let session:Session; try{session=await readJson<Session>(path.join(runDir,"session.json"));}catch{throw new Error("Missing or invalid required artifact: session.json");}
  if(session.status === "committed" || session.status === "aborted") throw new Error(`Cannot continue ${session.status} session ${session.sessionId}.`);
  if(!session.activeStepId) throw new Error("Cannot continue: session has no activeStepId.");
  let step:Step; try{ const dirs=(await readdir(path.join(runDir,"steps"))).sort(); const d=dirs.find(x=>x.endsWith(`-${session.activeStepId}`)); if(!d) throw new Error(); step=await readJson<Step>(path.join(runDir,"steps",d,"step.json")); }catch{throw new Error(`Missing or invalid required artifact for active step: ${session.activeStepId}`);}
  if(["accepted","rejected","superseded","running"].includes(step.status)) throw new Error(`Cannot continue ${step.status} step ${step.stepId}.`);
  const stepDir=await findStepDir(runDir, step); const request=await readFile(path.join(stepDir,"request.md"),"utf8").catch(()=>{missing.push(path.relative(runDir,path.join(stepDir,"request.md"))); return step.request;});
  const attempts=await loadAttempts(runDir, step, missing, invalid); if(invalid.length) throw new Error(`Invalid required artifact: ${invalid.join(", ")}`);
  const last=attempts.at(-1); const decision=await loadDecision(runDir, step, missing);
  const validation=await readOptionalJson<any>(runDir, last?.artifacts.validationReportPath, missing, invalid);
  const review=await readOptionalJson<any>(runDir, last?.artifacts.reviewReportPath, missing, invalid);
  const window=attempts.slice(-ATTEMPT_LIMIT); const omitted=Math.max(0, attempts.length-window.length);
  const previousAttempts:ContinueAttemptSummary[]=await Promise.all(window.map(async a=>{ const v=await readOptionalJson<any>(runDir,a.artifacts.validationReportPath,missing,invalid); const r=await readOptionalJson<any>(runDir,a.artifacts.reviewReportPath,missing,invalid); return { order:a.order, status:a.status, changedFiles:uniq(a.changedFiles), validationStatus:v?.status ?? a.validationSummary, reviewVerdict:r?.verdict, blockingFindings:reviewBlocking(r), warnings:reviewWarnings(r), errorSummary:a.errorSummary, artifactReferences:Object.fromEntries(Object.entries(a.artifacts ?? {}).filter(([,v])=>typeof v === "string")) as Record<string,string> }; }));
  const runtimeErrors=uniq([last?.status === "failed" || last?.status === "timed_out" ? last.errorSummary ?? last.resultStatus ?? last.status : undefined]);
  const requestedChanges=uniq([decision?.reason].filter(()=>decision?.type === "retry" || decision?.type === "revise"));
  const blocking=uniq([...reviewBlocking(review), ...requestedChanges, ...validationFailures(validation), ...runtimeErrors]);
  const warnings=reviewWarnings(review);
  const relevantFiles=uniq([...attempts.flatMap(a=>a.changedFiles), ...[...(review?.blockingFindings ?? []), ...(review?.warnings ?? [])].flatMap(filesFromFinding)]);
  let expectedValidation:ContinueValidationCommand[]=[]; try { const loaded=await loadProjectConfig("projects/demo.yaml", options.cwd ?? process.cwd()); expectedValidation=buildValidationCommands(loaded.config.commands, loaded.config.validation).map(({name,command,required})=>({name,command,required})); } catch { missing.push("project-validation-config"); }
  const reason=determineReason(step, attempts, decision, validation, review);
  const pkg:ContinuePackage={ schemaVersion:1, generatedAt:now.toISOString(), session:{sessionId:session.sessionId, goal:session.goal, branch:session.branch, workspacePath:session.workspacePath}, activeStep:{stepId:step.stepId, order:step.order, title:step.title, request:request.trim(), status:step.status}, execution:{nextAttemptOrder:step.attempts.length+1, threadId:last?.codexThreadId, runtimeMode:last?.runtimeMode, reason, omittedPreviousAttempts:omitted}, previousAttempts, currentFindings:{blocking, warnings, validationFailures:validationFailures(validation), runtimeErrors}, humanDecision:decision ? {type:decision.type, reason:decision.reason, requestedChanges} : undefined, constraints:uniq([...SYSTEM_CONSTRAINTS, ...requestedChanges]), expectedValidation, relevantFiles, artifactReferences:Object.fromEntries(Object.entries(last?.artifacts ?? {}).filter(([,v])=>typeof v === "string")) as Record<string,string>, missingArtifacts:uniq(missing), recommendedAction:"run-step" };
  return clean(pkg);
}
export function renderContinuePackageMarkdown(pkg:ContinuePackage): string { const lines=["# AutoCodex Continue Package","","## Session Goal",pkg.session.goal,"","## Active Step",`- Step: ${pkg.activeStep.order} — ${pkg.activeStep.title}`,`- Status: ${pkg.activeStep.status}`,"","## Why This Attempt Exists",`- Reason: ${pkg.execution.reason}`,`- Next attempt order: ${pkg.execution.nextAttemptOrder}`,"","## Current Request",pkg.activeStep.request,"","## Previous Attempts",...(pkg.previousAttempts.length?pkg.previousAttempts.map(a=>`- Attempt ${a.order}: ${a.status}; files: ${a.changedFiles.join(", ")||"none"}; validation: ${line(a.validationStatus)}; review: ${line(a.reviewVerdict)}; errors: ${line(a.errorSummary)}`):["- none"]),"","## Blocking Findings",...(pkg.currentFindings.blocking.length?pkg.currentFindings.blocking.map(x=>`- ${x}`):["- none"]),"","## Warnings",...(pkg.currentFindings.warnings.length?pkg.currentFindings.warnings.map(x=>`- ${x}`):["- none"]),"","## Human Decision",pkg.humanDecision?`- ${pkg.humanDecision.type}${pkg.humanDecision.reason?`: ${pkg.humanDecision.reason}`:""}`:"- none","","## Relevant Files",...(pkg.relevantFiles.length?pkg.relevantFiles.map(x=>`- ${x}`):["- none"]),"","## Constraints",...pkg.constraints.map(x=>`- ${x}`),"","## Expected Validation",...(pkg.expectedValidation.length?pkg.expectedValidation.map(v=>`- ${v.name}: ${v.command} (${v.required?"required":"optional"})`):["- none"]),"","## Artifact References",...(Object.keys(pkg.artifactReferences).length?Object.entries(pkg.artifactReferences).map(([k,v])=>`- ${k}: ${v}`):["- none"]),"","## Missing Artifacts",...(pkg.missingArtifacts.length?pkg.missingArtifacts.map(x=>`- ${x}`):["- none"]),""]; return scrubContinue(lines.join("\n")); }
export function renderCodexPrompt(pkg:ContinuePackage): string { const prev=pkg.previousAttempts.length?pkg.previousAttempts.map(a=>`- Attempt ${a.order}: ${a.status}; validation ${line(a.validationStatus)}; review ${line(a.reviewVerdict)}; changed files ${a.changedFiles.join(", ")||"none"}; blockers ${a.blockingFindings.join("; ")||"none"}; errors ${line(a.errorSummary)}`).join("\n"):"- No previous attempts for this step."; const lines=["You are continuing an existing AutoCodex development session.","","# Session Goal",pkg.session.goal,"","# Current Step",`${pkg.activeStep.order}: ${pkg.activeStep.title}`,"","# Task",pkg.activeStep.request,"","# Why This Attempt Exists",pkg.execution.reason,"","# Previous Attempt Results",prev,"","# Required Changes",...(pkg.currentFindings.blocking.length?pkg.currentFindings.blocking.map(x=>`- ${x}`):["- Implement the current step request."]),"","# Constraints",...pkg.constraints.map(x=>`- ${x}`),"","# Relevant Files",...(pkg.relevantFiles.length?pkg.relevantFiles.map(x=>`- ${x}`):["- none recorded"]),"","# Validation",...(pkg.expectedValidation.length?pkg.expectedValidation.map(v=>`- ${v.command}`):["- No configured validation commands were found; report this limitation."]),"","# Output Requirements","- Provide a concise summary of changes made.","- List changed files.","- Report validation results.","- Report known limitations.","- Do not push.","- Do not merge.","- Do not remove session or audit artifacts.",""]; return scrubContinue(lines.join("\n")); }
export async function writeContinuePackage(runDir:string, now=new Date(), options:{cwd?:string}={}): Promise<{package:ContinuePackage; jsonPath:string; markdownPath:string; codexPromptPath:string}> { const pkg=await buildContinuePackage(runDir, now, options); const dir=path.join(runDir,"continue"); await mkdir(dir,{recursive:true}); const jsonPath=path.join(dir,"continue-package.json"); const markdownPath=path.join(dir,"continue-package.md"); const codexPromptPath=path.join(dir,"codex-prompt.md"); await writeFile(jsonPath, `${JSON.stringify(pkg,null,2)}\n`, "utf8"); await writeFile(markdownPath, `${renderContinuePackageMarkdown(pkg)}\n`, "utf8"); await writeFile(codexPromptPath, `${renderCodexPrompt(pkg)}\n`, "utf8"); return {package:pkg,jsonPath,markdownPath,codexPromptPath}; }
