import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildUiTimeline, getUiRunStatus } from "./uiViewModel.js";

async function readJson(file: string): Promise<unknown> { try { return JSON.parse(await readFile(file, "utf8")); } catch { return undefined; } }
async function listChanged(runDir: string): Promise<string[]> { const final = await readJson(path.join(runDir, "final-result.json")) as { finalChangedFiles?: string[] } | undefined; return final?.finalChangedFiles ?? []; }
async function listFiles(dir: string, name: string): Promise<string[]> { const out: string[] = []; async function walk(d: string): Promise<void> { let e; try { e = await readdir(d, { withFileTypes: true }); } catch { return; } for (const x of e) { const p = path.join(d, x.name); if (x.isDirectory()) await walk(p); else if (x.name === name) out.push(path.relative(dir, p)); } } await walk(dir); return out; }
export async function writeSessionReport(runDir: string): Promise<string> {
  const [input, session, finalResult] = await Promise.all([readJson(path.join(runDir,"input.json")), readJson(path.join(runDir,"session.json")), readJson(path.join(runDir,"final-result.json"))]);
  const rows = await buildUiTimeline(runDir); const status = await getUiRunStatus(runDir); const decisions = await listFiles(runDir, "decision.json"); const changed = await listChanged(runDir); const handoffs = await listFiles(runDir, "gpt-handoff.md");
  const md = [`# AutoCodex Session Report`, ``, `## Session metadata`, "```json", JSON.stringify({ input, session, finalResult, uiStatus: status }, null, 2), "```", ``, `## Task`, (input as { goal?: string } | undefined)?.goal ?? "-", ``, `## Steps`, `| # | Step | Status | Output | Time |`, `|---|---|---|---|---|`, ...rows.map(r => `| ${String(r.order).padStart(2,"0")} | ${r.label} | ${r.status} | ${r.output?.path ?? "-"} | ${r.durationSeconds ?? "-"} |`), ``, `## Step handoffs`, handoffs.length ? handoffs.map((h,i)=>`- Step ${i+1}: ${h}`).join("\n") : "- none recorded", ``, `## Attempts`, ...rows.filter(r=>r.type==="codex").map(r=>`- ${r.label}: ${r.status}`), ``, `## Decisions`, decisions.length ? decisions.map(d=>`- ${d}`).join("\n") : "- none recorded", ``, `## Validation`, ...rows.filter(r=>r.type==="validation").map(r=>`- ${r.status}: ${r.output?.path ?? "-"}`), ``, `## Review`, ...rows.filter(r=>r.type==="review").map(r=>`- ${r.status}: ${r.output?.path ?? "-"}`), ``, `## Changed files`, changed.length ? changed.map(f=>`- ${f}`).join("\n") : "- none recorded", ``, `## Commit`, "- not created by MVP UI", ``, `## PR handoff`, "- no GitHub API, push, merge, or remote PR is performed by MVP UI", ``, `## Known limitations`, "- STOP is best-effort for UI-started child processes.", "- Human Review actions are read-only guidance in the MVP UI.", ""].join("\n");
  const out = path.join(runDir, "AUTOCODEX_SESSION_REPORT.md"); await writeFile(out, md, "utf8"); return out;
}
