import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { buildUiTimeline, getUiRunStatus } from "./uiViewModel.js";

async function readJson(file: string): Promise<any> { try { return JSON.parse(await readFile(file, "utf8")); } catch { return undefined; } }
async function listChanged(runDir: string): Promise<string[]> { const final = await readJson(path.join(runDir, "final-result.json")); return final?.finalChangedFiles ?? final?.changedFiles?.map((f:any)=>f.path) ?? []; }
async function listFiles(dir: string, name: string): Promise<string[]> { const out: string[] = []; async function walk(d: string): Promise<void> { let e; try { e = await readdir(d, { withFileTypes: true }); } catch { return; } for (const x of e) { const p = path.join(d, x.name); if (x.isDirectory()) await walk(p); else if (x.name === name) out.push(path.relative(dir, p)); } } await walk(dir); return out; }
function duration(start?:string,end?:string){ if(!start||!end)return "-"; const ms=Date.parse(end)-Date.parse(start); return Number.isFinite(ms)?`${ms}ms`:"-"; }
function compact(v:unknown){ return typeof v === "string" && v.trim() ? v.trim() : "-"; }
export async function ensureStepResultArtifacts(runDir:string): Promise<Array<{label:string;path:string;kind:"step-report";readable:true}>>{
  const rows=await buildUiTimeline(runDir); const artifacts:Array<{label:string;path:string;kind:"step-report";readable:true}>=[];
  for(const row of rows){ const n=String(row.index).padStart(2,"0"); const slug=row.label.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").replace(/^run-/,"")||"step"; const rel=path.join("steps",`${n}-${slug}`,"result.md"); const abs=path.join(runDir,rel); await mkdir(path.dirname(abs),{recursive:true});
    const rework=row.status==="rework"; const reason=row.message || (rework ? "Review requested rework, but no reason was recorded." : "-");
    const md=[`# Step Result: ${row.label}`,"",`- step label: ${row.label}`,`- status: ${row.status}`,`- startedAt: ${row.startedAt ?? "-"}`,`- finishedAt: ${row.finishedAt ?? "-"}`,`- duration: ${row.durationMs ?? duration(row.startedAt,row.finishedAt)}`,`- concise summary: ${compact(row.message)}`,"","## Commands executed","- none recorded","","## Files created","- none recorded","","## Files modified","- none recorded","","## Files deleted","- none recorded","","## Final response or decision",`- ${compact(row.message)}`,"","## Error or rework reason",`- ${reason}`,
      ...(rework?["","## Review rework details",`- why rework was requested: ${reason}`,"- expected state: task acceptance criteria satisfied and required outputs present","- actual state: reviewer requested rework","- missing or invalid files: see review report and message above",`- review decision: ${row.status}`]:[]),""].join("\n");
    await writeFile(abs,md,"utf8"); artifacts.push({label:`${row.label} result`,path:rel,kind:"step-report",readable:true}); }
  return artifacts;
}
export async function writeSessionReport(runDir: string): Promise<string> {
  const stepArtifacts=await ensureStepResultArtifacts(runDir); const [input, session, finalResult] = await Promise.all([readJson(path.join(runDir,"input.json")), readJson(path.join(runDir,"session.json")), readJson(path.join(runDir,"final-result.json"))]);
  const rows = await buildUiTimeline(runDir); const status = await getUiRunStatus(runDir); const changed = await listChanged(runDir); const decisions = await listFiles(runDir,"decision.json");
  const repo=session?.git?.repositoryPath ?? input?.repositoryPath ?? "-"; const branch=session?.git?.runBranch ?? session?.branch ?? "-";
  const md=["# AutoCodex Session Report","","## Run",`- run ID: ${session?.runId ?? input?.runId ?? finalResult?.runId ?? path.basename(runDir)}`,`- status: ${status}`,`- duration: ${rows.length ? rows.reduce((a,r)=>a+(r.durationMs??0),0) : "-"}`,`- repository: ${repo}`,`- branch: ${branch}`,`- redacted workspace identifier: ${finalResult?.finalWorkspacePath || session?.workspacePath ? "<run-workspace>" : "-"}`,"","## Task",input?.goal ?? session?.goal ?? "-","","## Timeline",...rows.map(r=>`- ${r.label}: ${r.status}; duration=${r.durationMs ?? "-"}; summary=${r.message ?? "-"}; result artifact path=${r.artifactPath ?? r.output?.path ?? stepArtifacts.find(a=>a.label.startsWith(r.label))?.path ?? "-"}`),"","## Changed files",changed.length?changed.map(f=>`- ${f}`).join("\n"):"- none recorded","","## User outputs",Array.isArray(finalResult?.outputs)&&finalResult.outputs.length?finalResult.outputs.map((o:any)=>`- ${o.path}`).join("\n"):"- none recorded","","## Validation",...rows.filter(r=>r.id.endsWith(":validation")).map(r=>`- ${r.status}: ${r.message ?? "-"}`),"","## Review",...rows.filter(r=>r.id.endsWith(":review")).map(r=>`- ${r.status}: ${r.message ?? "-"}`),"","## Failure",finalResult?.error?JSON.stringify(finalResult.error,null,2):"- none","","## Final response",finalResult?.finalResponse ?? "-","","## Decisions",decisions.length?decisions.map(d=>`- ${d}`).join("\n"):"- none recorded",""] .join("\n");
  const out = path.join(runDir, "AUTOCODEX_SESSION_REPORT.md"); await writeFile(out, md, "utf8"); return out;
}
