import { chmod, mkdir, mkdtemp, readdir, realpath, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { BranchSummary, RepositoryOption } from "./repositoryDiscovery.js";
import { validateManualRepository, listRepositoryBranches, currentBranch, getManagedRepositoriesRoot } from "./repositoryDiscovery.js";
const execFileAsync=promisify(execFile);
export type GithubErrorCode="credentials_unavailable"|"authentication_failed"|"rate_limited"|"network_error"|"invalid_response";
export type GithubRepo={id:number;fullName:string;name:string;cloneUrl:string;sshUrl?:string;defaultBranch?:string;isPrivate?:boolean;htmlUrl?:string};
export type GithubStatus={available:boolean;error:string|null;code?:GithubErrorCode;detail?:string;diagnostic?:string};
export type GithubApiRepo={id:unknown;name:unknown;full_name:unknown;clone_url:unknown;ssh_url:unknown;default_branch:unknown;private:unknown;html_url:unknown};
export type CloneErrorCode="repository_not_found"|"branch_not_found"|"credentials_unavailable"|"clone_failed"|"clone_timeout"|"clone_target_conflict"|"clone_target_dirty"|"origin_mismatch"|"worktree_validation_failed"|"clone_not_found_after_refresh";
export type BranchCheckout={repositoryId:string;fullName:string;branch:string;localPath:string;headCommit:string;cloned:true};
export class CloneRepositoryError extends Error{constructor(public code:CloneErrorCode,message:string){super(message);}}
export type ExecLike=(file:string,args:string[],opts?:Record<string,unknown>)=>Promise<{stdout:string;stderr?:string}>;
export type FetchLike=(url:string|URL,init?:RequestInit)=>Promise<Response>;
const defaultExec:ExecLike=async(file,args,opts)=>execFileAsync(file,args,opts as Parameters<typeof execFile>[2]) as Promise<{stdout:string;stderr?:string}>;
const unavailable="GitHub repositories unavailable.";
export function githubToken(env:NodeJS.ProcessEnv=process.env){return env.GITHUB_TOKEN || env.GH_TOKEN || undefined;}
function safeDetail(code:GithubErrorCode, detail?:string){return {available:false,error:unavailable,code,detail:detail?.replace(/Bearer\s+\S+/gi,"Bearer [REDACTED]")};}
function isObject(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==="object"&&!Array.isArray(v);}
export function mapGithubRepo(raw:unknown):GithubRepo|undefined{ if(!isObject(raw))return undefined; const r=raw as GithubApiRepo; if(typeof r.id!=="number"||typeof r.name!=="string"||typeof r.full_name!=="string"||typeof r.clone_url!=="string"||typeof r.ssh_url!=="string"||typeof r.default_branch!=="string"||typeof r.private!=="boolean"||typeof r.html_url!=="string") return undefined; return {id:r.id,name:r.name,fullName:r.full_name,cloneUrl:r.clone_url,sshUrl:r.ssh_url,defaultBranch:r.default_branch,isPrivate:r.private,htmlUrl:r.html_url}; }
async function fetchPage(fetchImpl:FetchLike,url:URL,token:string,timeoutMs:number){ const ac=new AbortController(); const timer=setTimeout(()=>ac.abort(),timeoutMs); try{return await fetchImpl(url,{headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28","User-Agent":"CatOS-AutoCodex"},signal:ac.signal});}finally{clearTimeout(timer);} }
function hasNextPage(res:Response){ const link=res.headers.get("link")||""; return /<[^>]+>;\s*rel="next"/.test(link); }
function dedupeAndSortGithubRepos(repositories:GithubRepo[]){ const byId=new Map<number,GithubRepo>(); for(const repo of repositories) if(!byId.has(repo.id)) byId.set(repo.id,repo); return [...byId.values()].sort((a,b)=>a.fullName.localeCompare(b.fullName,undefined,{sensitivity:"base"}) || a.id-b.id); }
export async function githubReposFromToken(token:string,fetchImpl:FetchLike=fetch,timeoutMs=10000,maxPages=1000):Promise<{repositories:GithubRepo[];github:GithubStatus}>{ const repositories:GithubRepo[]=[]; try{ for(let page=1;page<=maxPages;page++){ const url=new URL("https://api.github.com/user/repos"); url.searchParams.set("per_page","100"); url.searchParams.set("affiliation","owner,collaborator,organization_member"); url.searchParams.set("visibility","all"); url.searchParams.set("sort","full_name"); url.searchParams.set("direction","asc"); url.searchParams.set("page",String(page)); const res=await fetchPage(fetchImpl,url,token,timeoutMs); if(res.status===401) return {repositories:[],github:safeDetail("authentication_failed","GitHub authentication failed.")}; if(res.status===403||res.status===429) return {repositories:[],github:safeDetail("rate_limited","GitHub API rate limited or token permissions are insufficient for complete repository access.")}; if(!res.ok) return {repositories:[],github:safeDetail("network_error",`GitHub API returned ${res.status}.`)}; let data:unknown; try{data=await res.json();}catch{return {repositories:[],github:safeDetail("invalid_response","Malformed GitHub API JSON.")};} if(!Array.isArray(data)) return {repositories:[],github:safeDetail("invalid_response","GitHub API response was not an array.")}; const mapped=data.map(mapGithubRepo).filter((r):r is GithubRepo=>!!r); if(mapped.length!==data.length) return {repositories:[],github:safeDetail("invalid_response","GitHub API response contained invalid repository items.")}; repositories.push(...mapped); if(!hasNextPage(res)) break; } return {repositories:dedupeAndSortGithubRepos(repositories),github:{available:true,error:null,diagnostic:"GitHub repositories loaded from /user/repos with per_page=100, visibility=all, affiliation=owner,collaborator,organization_member, paginated via Link rel=next."}}; }catch(e){ const name=e instanceof Error?e.name:""; return {repositories:[],github:safeDetail(name==="AbortError"?"network_error":"network_error",name==="AbortError"?"GitHub API request timed out.":"GitHub API network error.")}; } }
export async function githubRepos(exec:ExecLike=defaultExec,env:NodeJS.ProcessEnv=process.env,fetchImpl:FetchLike=fetch):Promise<{repositories:GithubRepo[];github:GithubStatus}>{ const token=githubToken(env); if(token) return githubReposFromToken(token,fetchImpl); try{ const {stdout}=await exec("gh",["api","--paginate","/user/repos?per_page=100&affiliation=owner,collaborator,organization_member&sort=full_name","--jq",".[] | {id:.id,fullName:.full_name,name:.name,cloneUrl:.clone_url,sshUrl:.ssh_url,defaultBranch:.default_branch,isPrivate:.private,htmlUrl:.html_url}"],{timeout:20000}); const repositories=dedupeAndSortGithubRepos(stdout.split(/\r?\n/).map(l=>l.trim()).filter(Boolean).map(l=>JSON.parse(l) as GithubRepo)); return {repositories,github:{available:true,error:null,diagnostic:"GitHub repositories loaded via gh api --paginate /user/repos?per_page=100&affiliation=owner,collaborator,organization_member&sort=full_name."}}; }catch{return {repositories:[],github:safeDetail("credentials_unavailable","No GitHub token or gh authentication available.")};} }
export async function githubBranches(repo:RepositoryOption, env:NodeJS.ProcessEnv=process.env, fetchImpl:FetchLike=fetch, exec:ExecLike=defaultExec):Promise<{branches:BranchSummary[]}>{ if(repo.source!=="github"||!repo.fullName) throw new CloneRepositoryError("repository_not_found","GitHub repository not found."); if(repo.cloneUrl&&!/^https:\/\/github\.com\//i.test(repo.cloneUrl)){ try{const {stdout}=await exec("git",["ls-remote","--heads",repo.cloneUrl],{timeout:20000,env:gitEnv()}); const branches=stdout.split(/\r?\n/).map(l=>l.match(/refs\/heads\/(.+)$/)?.[1]).filter((b):b is string=>!!b).sort().map(name=>({name,default:name===repo.defaultBranch})); return {branches};}catch{throw new CloneRepositoryError("branch_not_found","Unable to list remote branches.");} } const token=githubToken(env); if(!token) throw new CloneRepositoryError("credentials_unavailable","GitHub credentials are unavailable."); const branches:BranchSummary[]=[]; for(let page=1;page<=100;page++){ const url=new URL(`https://api.github.com/repos/${repo.fullName}/branches`); url.searchParams.set("per_page","100"); url.searchParams.set("page",String(page)); const res=await fetchPage(fetchImpl,url,token,10000); if(res.status===404) throw new CloneRepositoryError("repository_not_found","GitHub repository not found."); if(res.status===401||res.status===403) throw new CloneRepositoryError("credentials_unavailable","GitHub credentials are unavailable."); if(!res.ok) throw new CloneRepositoryError("branch_not_found","Unable to list remote branches."); const data=await res.json() as unknown; if(!Array.isArray(data)) throw new CloneRepositoryError("branch_not_found","Invalid branch response."); const pageBranches: BranchSummary[]=data.flatMap((branch:unknown)=>{ if(!isObject(branch)||typeof branch.name!=="string") return []; return [{name:branch.name,default:branch.name===repo.defaultBranch}]; }); branches.push(...pageBranches); if(data.length<100)break; } return {branches}; }
export function normalizeGithubRemote(raw?:string):string|undefined{ if(!raw)return undefined; const s=raw.trim().replace(/\/$/,""); const patterns=[/^git@github\.com:([^/]+)\/(.+?)(?:\.git)?$/i,/^https:\/\/github\.com\/([^/]+)\/(.+?)(?:\.git)?$/i,/^ssh:\/\/git@github\.com\/([^/]+)\/(.+?)(?:\.git)?$/i]; for(const p of patterns){const m=s.match(p); if(m){const owner=m[1]; const repo=m[2].replace(/\.git$/i,""); if(owner&&repo&&!repo.includes("/")) return `${owner.toLowerCase()}/${repo.toLowerCase()}`;}} return undefined; }
export function safeSegment(v:string){ if(!/^[A-Za-z0-9._-]+$/.test(v)||!v||v==="."||v===".."||v.includes("/")||path.isAbsolute(v)) throw new Error("Invalid GitHub repository identity."); return v; }
export function managedCloneRoot(env:NodeJS.ProcessEnv=process.env){return getManagedRepositoriesRoot(env);}
export function safeBranchPath(branch:string){ const raw=branch?.trim(); if(!raw) throw new CloneRepositoryError("branch_not_found","Selected branch does not exist."); if(path.isAbsolute(raw)||raw.split("/").some(part=>!part||part==="."||part==="..")) throw new CloneRepositoryError("branch_not_found","Invalid branch path."); return raw.split("/").map(part=>/^[A-Za-z0-9._-]+$/.test(part)?part:encodeURIComponent(part)).join(path.sep); }
export function cloneTarget(fullName:string,branch:string,root=managedCloneRoot()){ const [owner,repo]=fullName.split("/"); if(!owner||!repo||fullName.split("/").length!==2) throw new CloneRepositoryError("repository_not_found","Invalid GitHub repository identity."); const branchRoot=path.resolve(root,"Cloned",safeSegment(owner),safeSegment(repo)); const target=path.resolve(branchRoot,safeBranchPath(branch)); if(target!==branchRoot&&!target.startsWith(branchRoot+path.sep)) throw new CloneRepositoryError("clone_target_conflict","Clone target escapes branch root."); return target; }
export function originHasCredentials(url:string){return /\/\/[^/]*(:|@).*@/.test(url)||/oauth2:/i.test(url)||/gh[pousr]_[A-Za-z0-9_]+/.test(url);}
export async function localGithubIdentity(repoPath:string,exec:ExecLike=defaultExec){try{const {stdout}=await exec("git",["-C",repoPath,"remote","get-url","origin"],{timeout:5000});return normalizeGithubRemote(stdout.trim());}catch{return undefined;}}
function normalizeFullName(fullName?:string){return fullName?.toLowerCase();}
function managedPathIdentity(repoPath:string|undefined,root:string){ if(!repoPath)return undefined; const rel=path.relative(path.resolve(root,"Cloned"),path.resolve(repoPath)); if(!rel||rel.startsWith("..")||path.isAbsolute(rel))return undefined; const parts=rel.split(path.sep).filter(Boolean); if(parts.length<3)return undefined; const [owner,repo]=parts; try{safeSegment(owner); safeSegment(repo);}catch{return undefined;} return `${owner.toLowerCase()}/${repo.toLowerCase()}`; }
function githubIdentities(g:GithubRepo){return new Set([normalizeGithubRemote(g.cloneUrl),normalizeFullName(g.fullName)].filter((v):v is string=>!!v));}
export async function mergeRepositories(local:RepositoryOption[], gh:GithubRepo[], exec:ExecLike=defaultExec, env:NodeJS.ProcessEnv=process.env){ const byIdentity=new Map<string,RepositoryOption>(); const managedRoot=getManagedRepositoriesRoot(env); for(const r of local){ const repoPath=r.localPath ?? r.path; const identities=[repoPath ? await localGithubIdentity(repoPath,exec) : undefined, managedPathIdentity(repoPath,managedRoot), normalizeFullName(r.fullName)].filter((id):id is string=>!!id); const matching=gh.find(g=>identities.some(id=>githubIdentities(g).has(id))); const canonical=matching?.fullName ?? identities[0]; if(canonical) r.fullName=r.fullName ?? canonical; for(const id of identities){byIdentity.set(id,r);} if(matching){ for(const id of githubIdentities(matching)) byIdentity.set(id,r); } } const out=[...local]; for(const g of gh){const identities=githubIdentities(g); if([...identities].some(id=>byIdentity.has(id))) continue; out.push({id:`github:${g.fullName}`,source:"github",name:g.fullName,fullName:g.fullName,cloneUrl:g.cloneUrl,defaultBranch:g.defaultBranch,isPrivate:g.isPrivate,isAvailableLocally:false}); } return out; }
async function dirEmpty(p:string){try{return (await readdir(p)).length===0;}catch{return true;}}
async function isWorkTree(p:string){try{return (await execFileAsync("git",["-C",p,"rev-parse","--is-inside-work-tree"],{timeout:5000})).stdout.trim()==="true";}catch{return false;}}
async function askpass(){ const dir=await realpath(await mkdtemp(path.join(os.tmpdir(),"catos-askpass-"))); const file=path.join(dir,"askpass.sh"); await writeFile(file,"#!/bin/sh\ncase \"$1\" in\n*Username*) printf '%s\\n' x-access-token ;;\n*) printf '%s\\n' \"$GITHUB_TOKEN\" ;;\nesac\n","utf8"); await chmod(file,0o700); return {dir,file}; }
function gitEnv(extra:NodeJS.ProcessEnv={}):NodeJS.ProcessEnv{ const e:NodeJS.ProcessEnv={GIT_TERMINAL_PROMPT:"0"}; for(const k of ["PATH","HOME","TMPDIR","LANG","LC_ALL"]) if(process.env[k]) e[k]=process.env[k]; return {...e,...extra};}
async function headCommit(target:string,exec:ExecLike){return (await exec("git",["-C",target,"rev-parse","HEAD"],{timeout:5000})).stdout.trim();}
async function clean(target:string,exec:ExecLike){return !(await exec("git",["-C",target,"status","--porcelain"],{timeout:5000})).stdout.trim();}
async function validateExistingCheckout(target:string,branch:string,remote:RepositoryOption,exec:ExecLike){ if(!(await isWorkTree(target))) { if(!(await dirEmpty(target))) throw new CloneRepositoryError("clone_target_conflict","Clone target is not empty."); return false; } const cur=await currentBranch(target); if(cur!==branch) throw new CloneRepositoryError("clone_target_conflict","Existing clone is on a different branch."); const {stdout:originOut}=await exec("git",["-C",target,"remote","get-url","origin"],{timeout:5000}); const origin=originOut.trim(); if(originHasCredentials(origin)) throw new CloneRepositoryError("worktree_validation_failed","Credential material detected in origin URL."); const originIdentity=normalizeGithubRemote(origin); if(originIdentity&&remote.fullName&&originIdentity!==remote.fullName.toLowerCase()) throw new CloneRepositoryError("origin_mismatch","Clone target contains a different Git repository."); if(!originIdentity&&origin!==remote.cloneUrl) throw new CloneRepositoryError("origin_mismatch","Clone target contains a different Git repository."); if(!(await clean(target,exec))) throw new CloneRepositoryError("clone_target_dirty","Clone target has uncommitted changes."); return true; }
export async function cloneGithubRepository(repositoryId:string, branch:string, repositories:RepositoryOption[], exec:ExecLike=defaultExec,env:NodeJS.ProcessEnv=process.env){ if(!repositoryId.startsWith("github:")) throw new CloneRepositoryError("repository_not_found","Only GitHub repositories can be cloned."); safeBranchPath(branch); const remote=repositories.find(r=>r.id===repositoryId&&r.source==="github"); if(!remote?.fullName||!remote.cloneUrl) throw new CloneRepositoryError("repository_not_found","GitHub repository not found."); const target=cloneTarget(remote.fullName,branch,managedCloneRoot(env)); await mkdir(path.dirname(target),{recursive:true}); const exists=await stat(target).then(()=>true).catch(()=>false); const alreadyUsable=exists ? await validateExistingCheckout(target,branch,remote,exec) : false;
 const token=githubToken(env); let helper:{dir:string;file:string}|undefined; try{ if(!alreadyUsable){ const cloneEnv=gitEnv(); if(token){helper=await askpass(); cloneEnv.GIT_ASKPASS=helper.file; cloneEnv.GITHUB_TOKEN=token;} await exec("git",["clone","--branch",branch,"--single-branch","--depth","1",remote.cloneUrl,target],{timeout:120000,env:cloneEnv}).catch(e=>{throw new CloneRepositoryError(String(e?.message||e).includes("timed out")?"clone_timeout":"clone_failed","Git clone failed.");}); await exec("git",["-C",target,"remote","set-url","origin",remote.cloneUrl],{timeout:5000}); }
  const repo=await validateManualRepository(target).catch(()=>{throw new CloneRepositoryError("worktree_validation_failed","Cloned repository is not a valid Git worktree.");}); const cur=await currentBranch(target); if(cur!==branch) throw new CloneRepositoryError("worktree_validation_failed","Cloned repository is on the wrong branch."); const {stdout}=await exec("git",["-C",target,"remote","get-url","origin"],{timeout:5000}); if(originHasCredentials(stdout.trim())) throw new CloneRepositoryError("worktree_validation_failed","Credential material detected in origin URL."); if(!(await clean(target,exec))) throw new CloneRepositoryError("clone_target_dirty","Clone target has uncommitted changes."); const head=await headCommit(target,exec); const checkout:BranchCheckout={repositoryId,fullName:remote.fullName,branch,localPath:repo.path,headCommit:head,cloned:true}; const branches=await listRepositoryBranches(target); return {checkout,repository:{source:"local" as const,id:repo.path,name:repo.name,fullName:remote.fullName,localPath:repo.path,path:repo.path,currentBranch:cur,defaultBranch:remote.defaultBranch,isPrivate:remote.isPrivate,isAvailableLocally:true,branches},branch,headCommit:head}; }finally{ if(helper) await rm(helper.dir,{recursive:true,force:true}).catch(()=>undefined); } }
