import { chmod, mkdir, mkdtemp, readdir, realpath, rm, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { RepositoryOption } from "./repositoryDiscovery.js";
import { validateManualRepository, listRepositoryBranches, currentBranch } from "./repositoryDiscovery.js";
const execFileAsync=promisify(execFile);
export type GithubErrorCode="credentials_unavailable"|"authentication_failed"|"rate_limited"|"network_error"|"invalid_response";
export type GithubRepo={id:number;fullName:string;name:string;cloneUrl:string;sshUrl?:string;defaultBranch?:string;isPrivate?:boolean;htmlUrl?:string};
export type GithubStatus={available:boolean;error:string|null;code?:GithubErrorCode;detail?:string};
export type GithubApiRepo={id:unknown;name:unknown;full_name:unknown;clone_url:unknown;ssh_url:unknown;default_branch:unknown;private:unknown;html_url:unknown};
export type ExecLike=(file:string,args:string[],opts?:Record<string,unknown>)=>Promise<{stdout:string;stderr?:string}>;
export type FetchLike=(url:string|URL,init?:RequestInit)=>Promise<Response>;
const defaultExec:ExecLike=async(file,args,opts)=>execFileAsync(file,args,opts as Parameters<typeof execFile>[2]) as Promise<{stdout:string;stderr?:string}>;
const unavailable="GitHub repositories unavailable.";
export function githubToken(env:NodeJS.ProcessEnv=process.env){return env.GITHUB_TOKEN || env.GH_TOKEN || undefined;}
function safeDetail(code:GithubErrorCode, detail?:string){return {available:false,error:unavailable,code,detail:detail?.replace(/Bearer\s+\S+/gi,"Bearer [REDACTED]")};}
function isObject(v:unknown):v is Record<string,unknown>{return !!v&&typeof v==="object"&&!Array.isArray(v);}
export function mapGithubRepo(raw:unknown):GithubRepo|undefined{ if(!isObject(raw))return undefined; const r=raw as GithubApiRepo; if(typeof r.id!=="number"||typeof r.name!=="string"||typeof r.full_name!=="string"||typeof r.clone_url!=="string"||typeof r.ssh_url!=="string"||typeof r.default_branch!=="string"||typeof r.private!=="boolean"||typeof r.html_url!=="string") return undefined; return {id:r.id,name:r.name,fullName:r.full_name,cloneUrl:r.clone_url,sshUrl:r.ssh_url,defaultBranch:r.default_branch,isPrivate:r.private,htmlUrl:r.html_url}; }
async function fetchPage(fetchImpl:FetchLike,url:URL,token:string,timeoutMs:number){ const ac=new AbortController(); const timer=setTimeout(()=>ac.abort(),timeoutMs); try{return await fetchImpl(url,{headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28","User-Agent":"CatOS-AutoCodex"},signal:ac.signal});}finally{clearTimeout(timer);} }
export async function githubReposFromToken(token:string,fetchImpl:FetchLike=fetch,timeoutMs=10000,maxPages=100):Promise<{repositories:GithubRepo[];github:GithubStatus}>{ const repositories:GithubRepo[]=[]; try{ for(let page=1;page<=maxPages;page++){ const url=new URL("https://api.github.com/user/repos"); url.searchParams.set("per_page","100"); url.searchParams.set("affiliation","owner,collaborator,organization_member"); url.searchParams.set("sort","full_name"); url.searchParams.set("page",String(page)); const res=await fetchPage(fetchImpl,url,token,timeoutMs); if(res.status===401) return {repositories:[],github:safeDetail("authentication_failed","GitHub authentication failed.")}; if(res.status===403||res.status===429) return {repositories:[],github:safeDetail("rate_limited","GitHub API rate limited.")}; if(!res.ok) return {repositories:[],github:safeDetail("network_error",`GitHub API returned ${res.status}.`)}; let data:unknown; try{data=await res.json();}catch{return {repositories:[],github:safeDetail("invalid_response","Malformed GitHub API JSON.")};} if(!Array.isArray(data)) return {repositories:[],github:safeDetail("invalid_response","GitHub API response was not an array.")}; const mapped=data.map(mapGithubRepo).filter((r):r is GithubRepo=>!!r); if(mapped.length!==data.length) return {repositories:[],github:safeDetail("invalid_response","GitHub API response contained invalid repository items.")}; repositories.push(...mapped); if(data.length<100) break; } return {repositories,github:{available:true,error:null}}; }catch(e){ const name=e instanceof Error?e.name:""; return {repositories:[],github:safeDetail(name==="AbortError"?"network_error":"network_error",name==="AbortError"?"GitHub API request timed out.":"GitHub API network error.")}; } }
export async function githubRepos(exec:ExecLike=defaultExec,env:NodeJS.ProcessEnv=process.env,fetchImpl:FetchLike=fetch):Promise<{repositories:GithubRepo[];github:GithubStatus}>{ const token=githubToken(env); if(token) return githubReposFromToken(token,fetchImpl); try{ const {stdout}=await exec("gh",["api","--paginate","/user/repos?per_page=100&affiliation=owner,collaborator,organization_member&sort=full_name","--jq",".[] | {id:.id,fullName:.full_name,name:.name,cloneUrl:.clone_url,sshUrl:.ssh_url,defaultBranch:.default_branch,isPrivate:.private,htmlUrl:.html_url}"],{timeout:20000}); const repositories=stdout.split(/\r?\n/).map(l=>l.trim()).filter(Boolean).map(l=>JSON.parse(l) as GithubRepo); return {repositories,github:{available:true,error:null}}; }catch{return {repositories:[],github:safeDetail("credentials_unavailable","No GitHub token or gh authentication available.")};} }
export function normalizeGithubRemote(raw?:string):string|undefined{ if(!raw)return undefined; const s=raw.trim().replace(/\/$/,""); const patterns=[/^git@github\.com:([^/]+)\/(.+?)(?:\.git)?$/i,/^https:\/\/github\.com\/([^/]+)\/(.+?)(?:\.git)?$/i,/^ssh:\/\/git@github\.com\/([^/]+)\/(.+?)(?:\.git)?$/i]; for(const p of patterns){const m=s.match(p); if(m){const owner=m[1]; const repo=m[2].replace(/\.git$/i,""); if(owner&&repo&&!repo.includes("/")) return `${owner.toLowerCase()}/${repo.toLowerCase()}`;}} return undefined; }
export function safeSegment(v:string){ if(!/^[A-Za-z0-9._-]+$/.test(v)||!v||v==="."||v===".."||v.includes("/")||path.isAbsolute(v)) throw new Error("Invalid GitHub repository identity."); return v; }
export function managedCloneRoot(){return process.env.CATOS_REPOSITORIES_ROOT || "/home/runner/catos-repositories";}
export function cloneTarget(fullName:string,root=managedCloneRoot()){ const [owner,repo]=fullName.split("/"); if(!owner||!repo||fullName.split("/").length!==2) throw new Error("Invalid GitHub repository identity."); const target=path.resolve(root,safeSegment(owner),safeSegment(repo)); const resolvedRoot=path.resolve(root); if(!target.startsWith(resolvedRoot+path.sep)) throw new Error("Clone target escapes managed root."); return target; }
export function originHasCredentials(url:string){return /\/\/[^/]*(:|@).*@/.test(url)||/oauth2:/i.test(url)||/gh[pousr]_[A-Za-z0-9_]+/.test(url);}
export async function localGithubIdentity(repoPath:string,exec:ExecLike=defaultExec){try{const {stdout}=await exec("git",["-C",repoPath,"remote","get-url","origin"],{timeout:5000});return normalizeGithubRemote(stdout.trim());}catch{return undefined;}}
function managedCloneIdentity(repoPath:string, fullName:string){try{return path.resolve(repoPath)===cloneTarget(fullName) ? fullName.toLowerCase() : undefined;}catch{return undefined;}}
export async function mergeRepositories(local:RepositoryOption[], gh:GithubRepo[], exec:ExecLike=defaultExec){ const byIdentity=new Map<string,RepositoryOption>(); for(const r of local){const remoteId=await localGithubIdentity(r.localPath!,exec); const managedId=gh.map(g=>managedCloneIdentity(r.localPath!,g.fullName)).find(Boolean); const id=remoteId ?? managedId; if(id){r.fullName=r.fullName ?? id; byIdentity.set(id.toLowerCase(),r);} } const out=[...local]; for(const g of gh){const ident=normalizeGithubRemote(g.cloneUrl) ?? g.fullName.toLowerCase(); if(byIdentity.has(ident)) continue; out.push({id:`github:${g.fullName}`,source:"github",name:g.fullName,fullName:g.fullName,cloneUrl:g.cloneUrl,defaultBranch:g.defaultBranch,isPrivate:g.isPrivate,isAvailableLocally:false}); } return out; }
async function dirEmpty(p:string){try{return (await readdir(p)).length===0;}catch{return true;}}
async function isWorkTree(p:string){try{return (await execFileAsync("git",["-C",p,"rev-parse","--is-inside-work-tree"],{timeout:5000})).stdout.trim()==="true";}catch{return false;}}
async function askpass(){ const dir=await realpath(await mkdtemp(path.join(os.tmpdir(),"catos-askpass-"))); const file=path.join(dir,"askpass.sh"); await writeFile(file,"#!/bin/sh\ncase \"$1\" in\n*Username*) printf '%s\\n' x-access-token ;;\n*) printf '%s\\n' \"$GITHUB_TOKEN\" ;;\nesac\n","utf8"); await chmod(file,0o700); return {dir,file}; }
export async function cloneGithubRepository(repositoryId:string, repositories:RepositoryOption[], exec:ExecLike=defaultExec,env:NodeJS.ProcessEnv=process.env){ if(!repositoryId.startsWith("github:")) throw new Error("Only GitHub repositories can be cloned."); const remote=repositories.find(r=>r.id===repositoryId&&r.source==="github"); if(!remote?.fullName||!remote.cloneUrl) throw new Error("GitHub repository not found."); const target=cloneTarget(remote.fullName); await mkdir(path.dirname(target),{recursive:true}); const exists=await stat(target).then(()=>true).catch(()=>false); if(exists){ if(await isWorkTree(target)){ const ident=await localGithubIdentity(target,exec); if(ident===remote.fullName.toLowerCase()){ const repo=await validateManualRepository(target); return {source:"local" as const,id:repo.path,name:repo.name,fullName:remote.fullName,localPath:repo.path,path:repo.path,currentBranch:repo.currentBranch,defaultBranch:remote.defaultBranch,isPrivate:remote.isPrivate,isAvailableLocally:true}; } throw new Error("Clone target contains a different Git repository."); } if(!(await dirEmpty(target))) throw new Error("Clone target is not empty."); } const token=githubToken(env); let helper:{dir:string;file:string}|undefined; try{ const cloneEnv:NodeJS.ProcessEnv={...process.env,GIT_TERMINAL_PROMPT:"0"}; if(token){helper=await askpass(); cloneEnv.GIT_ASKPASS=helper.file; cloneEnv.GITHUB_TOKEN=token;} await exec("git",["clone",remote.cloneUrl,target],{timeout:120000,env:cloneEnv}); await exec("git",["-C",target,"remote","set-url","origin",remote.cloneUrl],{timeout:5000}); const {stdout}=await exec("git",["-C",target,"remote","get-url","origin"],{timeout:5000}); if(originHasCredentials(stdout.trim())) throw new Error("Credential material detected in origin URL."); const repo=await validateManualRepository(target); const branches=await listRepositoryBranches(target); const cur=await currentBranch(target); return {source:"local" as const,id:repo.path,name:repo.name,fullName:remote.fullName,localPath:repo.path,path:repo.path,currentBranch:cur,defaultBranch:remote.defaultBranch,isPrivate:remote.isPrivate,isAvailableLocally:true,branches}; }finally{ if(helper) await rm(helper.dir,{recursive:true,force:true}).catch(()=>undefined); } }
