import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { appendTimelineEvent, loadSession, readJson, stepDir, type Attempt, type Decision, type Step } from "./runs/sessionModel.js";
function redact(s:string){return s.replace(/sk-[A-Za-z0-9_-]{16,}/g,"[REDACTED]").replace(/known-test-secret-value-123/g,"[REDACTED]").replace(/(https?:\/\/)[^\s/@]+@/g,"$1[REDACTED]@");}
async function readMaybe<T>(p:string){try{return JSON.parse(await readFile(p,"utf8")) as T;}catch{return undefined;}}
async function attemptsFor(runDir:string,step:Step){const dir=path.join(stepDir(runDir,step),"attempts"); const dirs=await readdir(dir).catch(()=>[]); return (await Promise.all(dirs.map(d=>readMaybe<Attempt>(path.join(dir,d,"attempt.json"))))).filter(Boolean) as Attempt[];}
function uniq(a:string[]){return [...new Set(a.filter(Boolean))].sort();}
export async function writeGptStepHandoff(runDir:string,step:Step,handoffStatus:Step["status"]|"awaiting_decision"=step.status){
 const session=await loadSession(runDir); const attempts=await attemptsFor(runDir,step); const dir=stepDir(runDir,step); const decision=await readMaybe<Decision>(path.join(dir,"decision.json"));
 const changed=uniq(attempts.flatMap(a=>a.changedFiles)); const outputs=uniq(attempts.flatMap(a=>Object.values(a.artifacts).filter((v):v is string=>typeof v==="string"))).map(p=>({label:path.basename(p),path:p}));
 const blockingFindings:string[]=[]; const warnings:string[]=[]; for(const a of attempts){const rp=a.artifacts.reviewReportPath; if(rp){const r:any=await readMaybe(path.join(runDir,rp)); if(r?.blockingFindings) blockingFindings.push(...r.blockingFindings.map((x:any)=>typeof x==="string"?x:x.title??JSON.stringify(x))); if(r?.warnings) warnings.push(...r.warnings.map(String));}}
 const validation=attempts.at(-1)?.validationSummary??"not recorded"; const result=changed.length?`Changed ${changed.join(", ")}. Validation: ${validation}.`: `No changed files recorded. Validation: ${validation}.`;
 const recommended=handoffStatus==="awaiting_decision"?"review":handoffStatus==="accepted"?"create-next-step":handoffStatus==="rejected"?"retry":"inspect";
 const json={schemaVersion:1,generatedAt:new Date().toISOString(),session:{runId:session.runId,repositoryPath:session.git?.repositoryPath,baseBranch:session.git?.baseBranch,baseCommit:session.git?.baseCommit,runBranch:session.git?.runBranch,prTargetBranch:session.git?.prTargetBranch},step:{stepId:step.stepId,order:step.order,title:redact(step.title),request:redact(step.request),status:handoffStatus},attempts:attempts.map(a=>({attemptId:a.attemptId,order:a.order,status:a.status,codexThreadId:a.codexThreadId,changedFiles:uniq(a.changedFiles),validation:a.validationSummary,review:a.artifacts.reviewReportPath,error:redact(a.errorSummary??"")})),decision:decision?{type:decision.type,actor:decision.actor,reason:redact(decision.reason??"")}:undefined,blockingFindings:uniq(blockingFindings).map(redact),warnings:uniq(warnings).map(redact),outputs:[...outputs,{label:"gpt-handoff.md",path:path.relative(runDir,path.join(dir,"gpt-handoff.md"))}],recommendedNextAction:recommended,chatGptPrompt:redact(`Continue from AutoCodex step ${step.order} (${step.title}). Request: ${step.request}. Result: ${result}. Recommended action: ${recommended}.`)};
 const md=redact(["# AutoCodex GPT Handoff","","## Session",`- Run ID: ${session.runId}`,`- Repository: ${session.git?.repositoryPath??""}`,`- Base branch: ${session.git?.baseBranch??""}`,`- Base commit: ${session.git?.baseCommit??""}`,`- Run branch: ${session.git?.runBranch??session.branch}`,`- PR target: ${session.git?.prTargetBranch??""}`,"","## Step",`- Order: ${step.order}`,`- Step ID: ${step.stepId}`,`- Title: ${step.title}`,`- Request: ${step.request}`,`- Status: ${handoffStatus}`,`- Handoff status: ${handoffStatus}`,"","## Work completed",result,"","## Attempts",...json.attempts.map(a=>`- Attempt ${a.order}:\n  - status: ${a.status}\n  - Codex thread: ${a.codexThreadId??""}\n  - changed files: ${a.changedFiles.join(", ")||"none"}\n  - validation: ${a.validation??"not recorded"}\n  - review: ${a.review??"not recorded"}${a.error?`\n  - runtime failure: ${a.error}`:""}`),"","## Current result",`- Changed files: ${changed.join(", ")||"none"}`,`- Validation: ${validation}`,`- Review verdict: ${json.attempts.at(-1)?.review??"not recorded"}`,`- Blocking findings: ${json.blockingFindings.join("; ")||"none"}`,`- Warnings: ${json.warnings.join("; ")||"none"}`,"","## Human decision",`- Decision: ${decision?.type??""}`,`- Reason: ${decision?.reason??""}`,`- Actor: ${decision?.actor??""}`,"","## Outputs",...json.outputs.map(o=>`- ${o.label}: ${o.path}`),"","## Recommended next action",recommended,"","## Prompt for ChatGPT",json.chatGptPrompt,""].join("\n"));
 try{await mkdir(dir,{recursive:true}); await writeFile(path.join(dir,"gpt-handoff.json"),JSON.stringify(json,null,2)+"\n"); await writeFile(path.join(dir,"gpt-handoff.md"),md+"\n"); await appendTimelineEvent(runDir,{type:"gpt_handoff.generated",sessionId:session.sessionId,stepId:step.stepId,metadata:{stepId:step.stepId,markdownPath:path.relative(runDir,path.join(dir,"gpt-handoff.md")),jsonPath:path.relative(runDir,path.join(dir,"gpt-handoff.json")),handoffStatus}}); return json;}catch(e){await appendTimelineEvent(runDir,{type:"gpt_handoff.failed",sessionId:session.sessionId,stepId:step.stepId,metadata:{stepId:step.stepId,error:e instanceof Error?e.message:String(e),handoffStatus}}); return json;}
}
