import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { spawn, type ChildProcess } from "node:child_process";
import { loadProjectConfig } from "./config/loadConfig.js";
import { buildUiSystemState, buildUiTimeline, getUiRunStatus } from "./uiViewModel.js";
import { writeSessionReport } from "./finalExport.js";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
const execFileAsync = promisify(execFile);
const active = new Map<string, ChildProcess>();
export type UiContext = { cwd?: string; runsDir?: string };
const cwdOf = (c?: UiContext) => c?.cwd ?? process.cwd(); const runsOf = (c?: UiContext) => c?.runsDir ?? path.join(cwdOf(c), "runs");
async function exists(p:string){try{await stat(p);return true;}catch{return false;}}
export async function listProjects(ctx: UiContext = {}) { const dir=path.join(cwdOf(ctx),"projects"); const files=(await readdir(dir)).filter(f=>f.endsWith(".yaml")||f.endsWith(".yml")); return Promise.all(files.map(async f=>{ const id=path.basename(f,path.extname(f)); const l=await loadProjectConfig(`projects/${f}`, cwdOf(ctx)); return { id, name:l.config.project.name, repository:l.absoluteRepoPath, baseBranch:l.config.project.baseBranch, prTarget:l.config.git.prTargetBranch ?? l.config.project.baseBranch ?? "", sandbox:l.config.codex.sandboxMode }; })); }
export async function getProjectConfig(projectId:string, ctx:UiContext={}) { return (await listProjects(ctx)).find(p=>p.id===projectId); }
async function branchExists(repo:string, branch:string){ try{ await execFileAsync("git",["-C",repo,"rev-parse","--verify",`${branch}^{commit}`]); return true;}catch{return false;} }
export async function startRun(input:{projectId:string; task:string; baseBranch:string; prTarget:string}, ctx:UiContext={}) { const p=await getProjectConfig(input.projectId,ctx); if(!p) throw new Error("Unknown project"); if(!(await exists(path.join(p.repository,".git")))) throw new Error("Invalid repository"); if(!(await branchExists(p.repository,input.baseBranch))) throw new Error("Missing base branch"); if(input.prTarget && !(await branchExists(p.repository,input.prTarget))) throw new Error("Missing PR target"); const args=["run","src/index.ts","run","--project",input.projectId,"--task",input.task,"--base-branch",input.baseBranch,"--pr-target",input.prTarget||input.baseBranch]; const child=spawn("npx",["tsx",...args.slice(1)],{cwd:cwdOf(ctx),stdio:"ignore",env:{...process.env}}); const started=Date.now(); let runId=""; const poll=async()=>{ const dirs=(await readdir(runsOf(ctx),{withFileTypes:true}).catch(()=>[])).filter(d=>d.isDirectory()).map(d=>d.name).sort().reverse(); for(const d of dirs){ const f=path.join(runsOf(ctx),d,"input.json"); try{ const j=JSON.parse(await readFile(f,"utf8")); if(j.projectId===input.projectId && j.goal===input.task && Date.parse(j.createdAt)>=started-5000) return d;}catch{} } return "";}; for(let i=0;i<20 && !runId;i++){ await new Promise(r=>setTimeout(r,100)); runId=await poll(); } if(runId) active.set(runId, child); child.on("exit", async()=>{ if(runId){ active.delete(runId); await writeSessionReport(path.join(runsOf(ctx),runId)).catch(()=>undefined); }}); return { runId, status:"running" }; }
export async function getRunStatus(runId:string, ctx:UiContext={}) { const runDir=path.join(runsOf(ctx),runId); return { runId, status: await getUiRunStatus(runDir), system: await buildUiSystemState(runDir) }; }
export async function getRunTimeline(runId:string, ctx:UiContext={}) { return buildUiTimeline(path.join(runsOf(ctx),runId)); }
export async function readRunOutput(runId:string, requested:string, ctx:UiContext={}) { const root=path.resolve(runsOf(ctx),runId); const target=path.resolve(root,requested); if(!target.startsWith(root+path.sep) && target!==root) throw new Error("Path traversal rejected"); const ext=path.extname(target); if(![".md",".txt",".json",".diff",".log"].includes(ext)) throw new Error("Unsupported output type"); let content=await readFile(target,"utf8"); if(ext===".json") content=JSON.stringify(JSON.parse(content),null,2); if(content.length>200_000) content=content.slice(0,200_000)+"\n[truncated]"; return { path: path.relative(root,target), content }; }
export async function getFinalExport(runId:string, ctx:UiContext={}) { const runDir=path.join(runsOf(ctx),runId); const file=await writeSessionReport(runDir); return { path:path.basename(file) }; }
export async function stopRun(runId:string, ctx:UiContext={}) { const child=active.get(runId); if(!child) return { supported:false, status: await getUiRunStatus(path.join(runsOf(ctx),runId)) }; child.kill("SIGTERM"); const runDir=path.join(runsOf(ctx),runId); await writeFile(path.join(runDir,".ui-stopped"), new Date().toISOString(), "utf8").catch(()=>undefined); await writeSessionReport(runDir).catch(()=>undefined); return { supported:true, status:"stopped" }; }
export async function recordHumanDecision(){ throw new Error("Human Review decisions are read-only in MVP UI; use CLI Human Gate commands."); }
