import http from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getFinalExport, getProjectConfig, getRunStatus, getRunTimeline, listProjects, readRunOutput, startRun, stopRun } from "./uiApi.js";
const root=path.dirname(fileURLToPath(import.meta.url));
async function json(req:http.IncomingMessage){ const chunks:Buffer[]=[]; for await (const c of req) chunks.push(Buffer.from(c)); return chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{}; }
function send(res:http.ServerResponse, code:number, body:unknown){ res.writeHead(code,{"content-type":"application/json"}); res.end(JSON.stringify(body)); }
export function createUiServer(){ return http.createServer(async(req,res)=>{ try{ const url=new URL(req.url??"/","http://localhost"); if(req.method==="GET"&&url.pathname==="/"){ res.writeHead(200,{"content-type":"text/html"}); res.end(await readFile(path.join(root,"ui","index.html"),"utf8")); return;} if(req.method==="GET"&&url.pathname==="/app.css"){res.writeHead(200,{"content-type":"text/css"});res.end(await readFile(path.join(root,"ui","app.css"),"utf8"));return;} if(req.method==="GET"&&url.pathname==="/app.js"){res.writeHead(200,{"content-type":"text/javascript"});res.end(await readFile(path.join(root,"ui","app.js"),"utf8"));return;} if(req.method==="GET"&&url.pathname==="/api/projects") return send(res,200,{projects:await listProjects()}); const m=url.pathname.match(/^\/api\/projects\/([^/]+)$/); if(req.method==="GET"&&m) return send(res,200,{project:await getProjectConfig(m[1])}); if(req.method==="POST"&&url.pathname==="/api/runs") return send(res,200,await startRun(await json(req))); const r=url.pathname.match(/^\/api\/runs\/([^/]+)(?:\/(timeline|output|final-export|stop))?$/); if(r){ const runId=r[1], part=r[2]; if(req.method==="GET"&&!part) return send(res,200,await getRunStatus(runId)); if(req.method==="GET"&&part==="timeline") return send(res,200,{rows:await getRunTimeline(runId)}); if(req.method==="GET"&&part==="output") return send(res,200,await readRunOutput(runId,url.searchParams.get("path")??"")); if(req.method==="GET"&&part==="final-export") return send(res,200,await getFinalExport(runId)); if(req.method==="POST"&&part==="stop") return send(res,200,await stopRun(runId)); } send(res,404,{error:"Not found"}); }catch(e){ send(res,400,{error:e instanceof Error?e.message:String(e)}); } }); }
export async function uiCommand(args:string[]){ const port=Number(args[args.indexOf("--port")+1])||8787; const server=createUiServer(); await new Promise<void>(resolve=>server.listen(port,"127.0.0.1",resolve)); console.log(`AutoCodex UI: http://127.0.0.1:${port}`); }
