import http from "node:http";
import { access, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getFinalExport, getProjectConfig, getRunStatus, getRunTimeline, listProjects, readRunOutput, startRun, stopRun, listRepositories, listBranches, loadManualRepository, cloneRepository } from "./uiApi.js";
import { CloneRepositoryError } from "./githubRepositories.js";
const root=path.dirname(fileURLToPath(import.meta.url));
type UiAsset={file:string; contentType:string};
async function pathExists(file:string){ try{ await access(file); return true; }catch{return false;} }
async function resolveUiRoot(){ const candidates=[path.join(root,"ui"),path.join(root,"..","..","src","ui"),path.join(process.cwd(),"src","ui")]; for(const candidate of candidates){ if(await pathExists(path.join(candidate,"app.js"))) return candidate; } return candidates[0]; }
async function uiAssets(){ const uiRoot=await resolveUiRoot(); return new Map<string,UiAsset>([["/app.css",{file:path.join(uiRoot,"app.css"),contentType:"text/css; charset=utf-8"}],["/app.js",{file:path.join(uiRoot,"app.js"),contentType:"text/javascript; charset=utf-8"}],["/repositorySelection.js",{file:path.join(uiRoot,"repositorySelection.js"),contentType:"text/javascript; charset=utf-8"}]]); }
async function json(req:http.IncomingMessage){ const chunks:Buffer[]=[]; for await (const c of req) chunks.push(Buffer.from(c)); return chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{}; }
function send(res:http.ServerResponse, code:number, body:unknown){ res.writeHead(code,{"content-type":"application/json"}); res.end(JSON.stringify(body)); }
export function createUiServer(){ return http.createServer(async(req,res)=>{ try{ const url=new URL(req.url??"/","http://localhost"); if(req.method==="GET"&&url.pathname==="/"){ res.writeHead(200,{"content-type":"text/html; charset=utf-8"}); res.end(await readFile(path.join(await resolveUiRoot(),"index.html"),"utf8")); return;} if(req.method==="GET"){ const asset=(await uiAssets()).get(url.pathname); if(asset){res.writeHead(200,{"content-type":asset.contentType});res.end(await readFile(asset.file,"utf8"));return;} } if(req.method==="GET"&&url.pathname==="/api/projects") return send(res,200,{projects:await listProjects()}); if(req.method==="GET"&&url.pathname==="/api/repositories") return send(res,200,await listRepositories()); if(req.method==="POST"&&url.pathname==="/api/repositories/clone") { const body=await json(req); return send(res,200,await cloneRepository({repositoryId:body.repositoryId,branch:body.branch})); } if(req.method==="GET"&&url.pathname==="/api/branches") return send(res,200,await listBranches(url.searchParams.get("repositoryPath")??"",url.searchParams.get("repositoryId")??undefined)); if(req.method==="GET"&&url.pathname==="/api/github/branches") return send(res,200,await listBranches("",url.searchParams.get("repositoryId")??undefined)); if(req.method==="POST"&&url.pathname==="/api/repositories/manual") { const body=await json(req); return send(res,200,await loadManualRepository(body.repositoryPath)); } const m=url.pathname.match(/^\/api\/projects\/([^/]+)$/); if(req.method==="GET"&&m) return send(res,200,{project:await getProjectConfig(m[1])}); if(req.method==="POST"&&url.pathname==="/api/runs") return send(res,200,await startRun(await json(req))); const r=url.pathname.match(/^\/api\/runs\/([^/]+)(?:\/(timeline|output|final-export|stop))?$/); if(r){ const runId=r[1], part=r[2]; if(req.method==="GET"&&!part) return send(res,200,await getRunStatus(runId)); if(req.method==="GET"&&part==="timeline") return send(res,200,{rows:await getRunTimeline(runId)}); if(req.method==="GET"&&part==="output") return send(res,200,await readRunOutput(runId,url.searchParams.get("path")??"")); if(req.method==="GET"&&part==="final-export") return send(res,200,await getFinalExport(runId)); if(req.method==="POST"&&part==="stop") return send(res,200,await stopRun(runId)); } send(res,404,{error:{code:"not_found",message:"Not found"}}); }catch(e){ const err=e instanceof CloneRepositoryError?{code:e.code,message:e.message}:{code:"request_failed",message:e instanceof Error?e.message:String(e)}; send(res,400,{error:err}); } }); }
export async function uiCommand(args:string[]){ const port=Number(args[args.indexOf("--port")+1])||8787; const host=args.includes("--host")?args[args.indexOf("--host")+1]:"127.0.0.1"; const server=createUiServer(); await new Promise<void>(resolve=>server.listen(port,host,resolve)); console.log(`AutoCodex UI: http://${host}:${port}`); }
